Partial Public Class dbAMPLIACIONCONTRATO

    Public Function obtenerAmpliacionContrato(ByVal IDESTABLECIMIENTO As Integer, ByVal IDPROCESOCOMPRA As Integer) As DataSet

        Dim strSQL As New Text.StringBuilder
        strSQL.Append(" SELECT SAB_UTMIM_AMPLIACIONCONTRATO.IDESTABLECIMIENTO, SAB_UTMIM_AMPLIACIONCONTRATO.IDPROCESOCOMPRA, ")
        strSQL.Append(" SAB_CAT_PROVEEDORES.NOMBRE AS PROVEEDOR, SAB_UTMIM_AMPLIACIONCONTRATO.IDCONTRATO, ")
        strSQL.Append(" SAB_UTMIM_AMPLIACIONCONTRATO.IDAMPLIACIONCONTRATO, SAB_UTMIM_AMPLIACIONCONTRATO.RENGLON, ")
        strSQL.Append(" SAB_CAT_CATALOGOPRODUCTOS.NOMBRE AS NOMBRERENGLON, SAB_UTMIM_AMPLIACIONCONTRATO.CANTIDADAMPLIADA, SAB_UTMIM_AMPLIACIONCONTRATO.IDPROVEEDOR ")
        strSQL.Append(" FROM SAB_UTMIM_AMPLIACIONCONTRATO INNER JOIN ")
        strSQL.Append(" SAB_CAT_PROVEEDORES ON SAB_UTMIM_AMPLIACIONCONTRATO.IDPROVEEDOR = SAB_CAT_PROVEEDORES.IDPROVEEDOR INNER JOIN ")
        strSQL.Append(" SAB_UACI_DETALLEPROCESOCOMPRA ON ")
        strSQL.Append(" SAB_UTMIM_AMPLIACIONCONTRATO.IDESTABLECIMIENTO = SAB_UACI_DETALLEPROCESOCOMPRA.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UTMIM_AMPLIACIONCONTRATO.IDPROCESOCOMPRA = SAB_UACI_DETALLEPROCESOCOMPRA.IDPROCESOCOMPRA AND ")
        strSQL.Append(" SAB_UTMIM_AMPLIACIONCONTRATO.RENGLON = SAB_UACI_DETALLEPROCESOCOMPRA.RENGLON INNER JOIN ")
        strSQL.Append(" SAB_CAT_CATALOGOPRODUCTOS ON ")
        strSQL.Append(" SAB_UACI_DETALLEPROCESOCOMPRA.IDPRODUCTO = SAB_CAT_CATALOGOPRODUCTOS.IDPRODUCTO ")
        strSQL.Append(" WHERE (SAB_UTMIM_AMPLIACIONCONTRATO.IDESTABLECIMIENTO = " & IDESTABLECIMIENTO & ") AND (SAB_UTMIM_AMPLIACIONCONTRATO.IDPROCESOCOMPRA = " & IDPROCESOCOMPRA & ") ")

        Return SqlHelper.ExecuteDataset(Me.cnnStr, CommandType.Text, strSQL.ToString())

    End Function

    Public Function obtenerRenglonesAmpliados(ByVal IDESTABLECIMIENTO As Integer, ByVal IDPROCESOCOMPRA As Integer) As DataSet

        Dim strSQL As New Text.StringBuilder
        strSQL.Append(" SELECT SAB_UTMIM_AMPLIACIONCONTRATO.IDPROVEEDOR, SAB_UTMIM_AMPLIACIONCONTRATO.IDCONTRATO, ")
        strSQL.Append(" SAB_UTMIM_AMPLIACIONCONTRATO.IDAMPLIACIONCONTRATO, SAB_UTMIM_AMPLIACIONCONTRATO.RENGLON, ")
        strSQL.Append(" SAB_CAT_CATALOGOPRODUCTOS.CODIGO, SAB_CAT_CATALOGOPRODUCTOS.NOMBRE, ")
        strSQL.Append(" SAB_UTMIM_AMPLIACIONCONTRATO.CANTIDADAMPLIADA ")
        strSQL.Append(" FROM SAB_UTMIM_AMPLIACIONCONTRATO INNER JOIN ")
        strSQL.Append(" SAB_UACI_DETALLEPROCESOCOMPRA ON ")
        strSQL.Append(" SAB_UTMIM_AMPLIACIONCONTRATO.IDESTABLECIMIENTO = SAB_UACI_DETALLEPROCESOCOMPRA.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UTMIM_AMPLIACIONCONTRATO.IDPROCESOCOMPRA = SAB_UACI_DETALLEPROCESOCOMPRA.IDPROCESOCOMPRA AND ")
        strSQL.Append(" SAB_UTMIM_AMPLIACIONCONTRATO.RENGLON = SAB_UACI_DETALLEPROCESOCOMPRA.RENGLON INNER JOIN ")
        strSQL.Append(" SAB_CAT_CATALOGOPRODUCTOS ON ")
        strSQL.Append(" SAB_UACI_DETALLEPROCESOCOMPRA.IDPRODUCTO = SAB_CAT_CATALOGOPRODUCTOS.IDPRODUCTO ")
        strSQL.Append(" WHERE (SAB_UTMIM_AMPLIACIONCONTRATO.IDESTABLECIMIENTO = " & IDESTABLECIMIENTO & ") AND (SAB_UTMIM_AMPLIACIONCONTRATO.IDPROCESOCOMPRA = " & IDPROCESOCOMPRA & ") ")

        Return SqlHelper.ExecuteDataset(Me.cnnStr, CommandType.Text, strSQL.ToString())

    End Function

End Class
