Partial Public Class dbGARANTIASCONTRATOS

#Region " Metodos Agregados "

    Public Function ObtenerDataSetRenglones(ByVal IDESTABLECIMIENTO As Int32, ByVal IDPROVEEDOR As Int32, ByVal IDPROCESOCOMPRA As Int64) As DataSet

        Dim strSQL As New Text.StringBuilder
        strSQL.Append(" SELECT ")
        strSQL.Append("   DPC.RENGLON AS renglon, ")
        strSQL.Append("   ISNULL(A.CANTIDADFIRME, 0) AS cantidad, ")
        strSQL.Append("   ISNULL(DO.PRECIOUNITARIO, 0) AS precio, ")
        strSQL.Append("   ISNULL(DO.PRECIOUNITARIO * A.CANTIDADFIRME, 0) AS monto, ")
        strSQL.Append("   A.IDPROCESOCOMPRA, A.IDESTABLECIMIENTO, A.IDPROVEEDOR, ")
        strSQL.Append("   A.IDDETALLE ")
        strSQL.Append(" FROM ")
        strSQL.Append("   SAB_UACI_DETALLEPROCESOCOMPRA DPC ")
        strSQL.Append("     INNER JOIN SAB_UACI_ADJUDICACION A ")
        strSQL.Append("       ON DPC.IDPROCESOCOMPRA = A.IDPROCESOCOMPRA AND ")
        strSQL.Append("          DPC.IDESTABLECIMIENTO = A.IDESTABLECIMIENTO ")
        strSQL.Append("     INNER JOIN SAB_UACI_DETALLEOFERTA DO ")
        strSQL.Append("       ON A.IDPROCESOCOMPRA = DO.IDPROCESOCOMPRA AND ")
        strSQL.Append("          A.IDESTABLECIMIENTO = DO.IDESTABLECIMIENTO AND ")
        strSQL.Append("          A.IDPROVEEDOR = DO.IDPROVEEDOR AND ")
        strSQL.Append("          A.IDDETALLE = DO.IDDETALLE AND ")
        strSQL.Append("          DPC.IDESTABLECIMIENTO = DO.IDESTABLECIMIENTO AND ")
        strSQL.Append("          DPC.IDPROCESOCOMPRA = DO.IDPROCESOCOMPRA AND ")
        strSQL.Append("          DPC.RENGLON = DO.RENGLON ")
        strSQL.Append(" WHERE ")
        strSQL.Append("   A.IDPROCESOCOMPRA = @IDPROCESOCOMPRA AND ")
        strSQL.Append("   A.IDESTABLECIMIENTO = @IDESTABLECIMIENTO AND ")
        strSQL.Append("   A.IDPROVEEDOR = @IDPROVEEDOR AND")
        strSQL.Append("   A.CANTIDADFIRME > 0 ")

        Dim args(3) As SqlParameter
        args(0) = New SqlParameter("@IDESTABLECIMIENTO", SqlDbType.Int)
        args(0).Value = IDESTABLECIMIENTO
        args(1) = New SqlParameter("@IDPROVEEDOR", SqlDbType.Int)
        args(1).Value = IDPROVEEDOR
        args(2) = New SqlParameter("@IDPROCESOCOMPRA", SqlDbType.BigInt)
        args(2).Value = IDPROCESOCOMPRA

        Dim ds As DataSet
        ds = SqlHelper.ExecuteDataset(Me.cnnStr, CommandType.Text, strSQL.ToString(), args)

        Return ds

    End Function

    Public Function ObtenerDataSetProcesoCompra(ByVal IDESTABLECIMIENTO As Int32) As DataSet

        Dim strSQL As New Text.StringBuilder
        strSQL.Append("SELECT IDPROCESOCOMPRA, CODIGOLICITACION ")
        strSQL.Append("FROM SAB_UACI_PROCESOCOMPRAS ")
        strSQL.Append("WHERE (IDESTABLECIMIENTO = @IDESTABLECIMIENTO) ")

        Dim args(1) As SqlParameter
        args(0) = New SqlParameter("@IDESTABLECIMIENTO", SqlDbType.Int)
        args(0).Value = IDESTABLECIMIENTO

        Dim ds As DataSet
        ds = SqlHelper.ExecuteDataset(Me.cnnStr, CommandType.Text, strSQL.ToString(), args)

        Return ds

    End Function

    Public Function ObtenerDataSetProveedor() As DataSet

        Dim strSQL As New Text.StringBuilder
        strSQL.Append(" SELECT DISTINCT SAB_CAT_PROVEEDORES.IDPROVEEDOR, SAB_CAT_PROVEEDORES.NOMBRE, SAB_UACI_CONTRATOS.IDESTADOCONTRATO ")
        strSQL.Append("  FROM SAB_CAT_PROVEEDORES INNER JOIN ")
        strSQL.Append("  SAB_UACI_GARANTIASCONTRATOS ON SAB_CAT_PROVEEDORES.IDPROVEEDOR = SAB_UACI_GARANTIASCONTRATOS.IDPROVEEDOR INNER JOIN ")
        strSQL.Append("  SAB_UACI_CONTRATOS ON SAB_CAT_PROVEEDORES.IDPROVEEDOR = SAB_UACI_CONTRATOS.IDPROVEEDOR AND ")
        strSQL.Append("  SAB_UACI_GARANTIASCONTRATOS.IDESTABLECIMIENTO = SAB_UACI_CONTRATOS.IDESTABLECIMIENTO AND ")
        strSQL.Append("  SAB_UACI_GARANTIASCONTRATOS.IDPROVEEDOR = SAB_UACI_CONTRATOS.IDPROVEEDOR AND ")
        strSQL.Append("  SAB_UACI_GARANTIASCONTRATOS.IDCONTRATO = SAB_UACI_CONTRATOS.IDCONTRATO ")
        strSQL.Append("  WHERE(SAB_UACI_CONTRATOS.IDESTADOCONTRATO = 3) ")
        strSQL.Append("  ORDER BY SAB_CAT_PROVEEDORES.NOMBRE ")

        Dim ds As DataSet
        ds = SqlHelper.ExecuteDataset(Me.cnnStr, CommandType.Text, strSQL.ToString())

        Return ds

    End Function

    Public Function ObtenerDataSetBusquedaProcesoCompra(ByVal IDESTABLECIMIENTO As Int32, ByVal IDPROCESOCOMPRA As Int64) As DataSet

        Dim strSQL As New Text.StringBuilder
        strSQL.Append("SELECT SAB_UACI_PROCESOCOMPRAS.IDPROCESOCOMPRA, SAB_UACI_CONTRATOS.IDPROVEEDOR, ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA.IDCONTRATO, SAB_UACI_PROCESOCOMPRAS.CODIGOLICITACION, ")
        strSQL.Append(" SAB_UACI_RECEPCIONOFERTAS.ORDENLLEGADA, SAB_UACI_CONTRATOS.NUMEROCONTRATO, SAB_CAT_PROVEEDORES.NOMBRE, ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDESTABLECIMIENTO ")
        strSQL.Append(" FROM SAB_UACI_CONTRATOS INNER JOIN ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS ON SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = SAB_UACI_PROCESOCOMPRAS.IDESTABLECIMIENTO INNER JOIN ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA ON ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDPROVEEDOR = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDCONTRATO = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDCONTRATO AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDPROCESOCOMPRA = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROCESOCOMPRA AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDESTABLECIMIENTO = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDESTABLECIMIENTO INNER JOIN ")
        strSQL.Append(" SAB_CAT_PROVEEDORES ON SAB_UACI_CONTRATOS.IDPROVEEDOR = SAB_CAT_PROVEEDORES.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROVEEDOR = SAB_CAT_PROVEEDORES.IDPROVEEDOR INNER JOIN ")
        strSQL.Append(" SAB_UACI_RECEPCIONOFERTAS ON SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = SAB_UACI_RECEPCIONOFERTAS.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDPROVEEDOR = SAB_UACI_RECEPCIONOFERTAS.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDPROCESOCOMPRA = SAB_UACI_RECEPCIONOFERTAS.IDPROCESOCOMPRA AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDESTABLECIMIENTO = SAB_UACI_RECEPCIONOFERTAS.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROVEEDOR = SAB_UACI_RECEPCIONOFERTAS.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_CAT_PROVEEDORES.IDPROVEEDOR = SAB_UACI_RECEPCIONOFERTAS.IDPROVEEDOR ")
        strSQL.Append(" WHERE (SAB_UACI_PROCESOCOMPRAS.IDPROCESOCOMPRA = @IDPROCESOCOMPRA) AND ")
        strSQL.Append("  (SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = @IDESTABLECIMIENTO) ")

        Dim args(2) As SqlParameter
        args(0) = New SqlParameter("@IDESTABLECIMIENTO", SqlDbType.Int)
        args(0).Value = IDESTABLECIMIENTO
        args(1) = New SqlParameter("@IDPROCESOCOMPRA", SqlDbType.BigInt)
        args(1).Value = IDPROCESOCOMPRA

        Dim ds As DataSet
        ds = SqlHelper.ExecuteDataset(Me.cnnStr, CommandType.Text, strSQL.ToString(), args)

        Return ds

    End Function

    Public Function ObtenerDataSetBusquedaProveedor(ByVal IDESTABLECIMIENTO As Int32, ByVal IDPROVEEDOR As Int32) As DataSet

        Dim strSQL As New Text.StringBuilder
        strSQL.Append("SELECT SAB_UACI_PROCESOCOMPRAS.IDPROCESOCOMPRA, SAB_UACI_CONTRATOS.IDPROVEEDOR, ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA.IDCONTRATO, SAB_UACI_PROCESOCOMPRAS.CODIGOLICITACION, ")
        strSQL.Append(" SAB_UACI_RECEPCIONOFERTAS.ORDENLLEGADA, SAB_UACI_CONTRATOS.NUMEROCONTRATO, SAB_CAT_PROVEEDORES.NOMBRE, ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDESTABLECIMIENTO ")
        strSQL.Append(" FROM SAB_UACI_CONTRATOS INNER JOIN ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS ON SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = SAB_UACI_PROCESOCOMPRAS.IDESTABLECIMIENTO INNER JOIN ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA ON ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDPROVEEDOR = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDCONTRATO = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDCONTRATO AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDPROCESOCOMPRA = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROCESOCOMPRA AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDESTABLECIMIENTO = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDESTABLECIMIENTO INNER JOIN ")
        strSQL.Append(" SAB_CAT_PROVEEDORES ON SAB_UACI_CONTRATOS.IDPROVEEDOR = SAB_CAT_PROVEEDORES.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROVEEDOR = SAB_CAT_PROVEEDORES.IDPROVEEDOR INNER JOIN ")
        strSQL.Append(" SAB_UACI_RECEPCIONOFERTAS ON SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = SAB_UACI_RECEPCIONOFERTAS.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDPROVEEDOR = SAB_UACI_RECEPCIONOFERTAS.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDPROCESOCOMPRA = SAB_UACI_RECEPCIONOFERTAS.IDPROCESOCOMPRA AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDESTABLECIMIENTO = SAB_UACI_RECEPCIONOFERTAS.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROVEEDOR = SAB_UACI_RECEPCIONOFERTAS.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_CAT_PROVEEDORES.IDPROVEEDOR = SAB_UACI_RECEPCIONOFERTAS.IDPROVEEDOR ")
        strSQL.Append(" WHERE (SAB_UACI_CONTRATOS.IDPROVEEDOR = @IDPROVEEDOR) AND ")
        strSQL.Append(" (SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = @IDESTABLECIMIENTO) ")

        Dim args(2) As SqlParameter
        args(0) = New SqlParameter("@IDESTABLECIMIENTO", SqlDbType.Int)
        args(0).Value = IDESTABLECIMIENTO
        args(1) = New SqlParameter("@IDPROVEEDOR", SqlDbType.Int)
        args(1).Value = IDPROVEEDOR

        Dim ds As DataSet
        ds = SqlHelper.ExecuteDataset(Me.cnnStr, CommandType.Text, strSQL.ToString(), args)

        Return ds

    End Function

    Public Function obtenerDsRptProveedor(ByVal IDESTABLECIMIENTO As Integer, ByVal IDPROVEEDOR As Integer)

        Dim strSQL As New Text.StringBuilder
        strSQL.Append(" SELECT PC.IDPROCESOCOMPRA, C.IDPROVEEDOR, CPC.IDCONTRATO, RO.ORDENLLEGADA, C.IDESTABLECIMIENTO, GC.IDTIPOGARANTIA, ")
        strSQL.Append(" CONVERT(VARCHAR(10), GC.FECHARECEPCION, 103) AS FECHARECEPCION, GC.NUMEROGARANTIA, CONVERT(VARCHAR(10), ")
        strSQL.Append(" GC.FECHAVENCIMIENTO, 103) AS FECHAVENCIMIENTO, GC.VIGENCIA, GC.MONTO, GC.ASEGURADORA, PC.CODIGOLICITACION, ")
        strSQL.Append(" PC.NUMERORESOLUCION, C.NUMEROCONTRATO, PRO.NOMBRE AS PROVEEDOR, EG.DESCRIPCION AS ESTADO, CONVERT(VARCHAR(10), ")
        strSQL.Append(" GC.FECHAEFECTIVA, 103) AS FECHAEFECTIVA, CONVERT(VARCHAR(10), GC.FECHADEVOLUCION, 103) AS FECHADEVOLUCION, ")
        strSQL.Append(" CONVERT(VARCHAR(10), dateadd(mm,36,GC.FECHAVENCIMIENTO), 103) AS FECHAEXPIRACION, TG.NOMBRE AS TIPO ")
        strSQL.Append(" FROM SAB_UACI_CONTRATOS AS C INNER JOIN ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS AS PC ON C.IDESTABLECIMIENTO = PC.IDESTABLECIMIENTO INNER JOIN ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA AS CPC ON C.IDESTABLECIMIENTO = CPC.IDESTABLECIMIENTO AND ")
        strSQL.Append(" C.IDPROVEEDOR = CPC.IDPROVEEDOR AND C.IDCONTRATO = CPC.IDCONTRATO AND PC.IDPROCESOCOMPRA = CPC.IDPROCESOCOMPRA AND ")
        strSQL.Append(" PC.IDESTABLECIMIENTO = CPC.IDESTABLECIMIENTO INNER JOIN ")
        strSQL.Append(" SAB_CAT_PROVEEDORES AS PRO ON C.IDPROVEEDOR = PRO.IDPROVEEDOR AND CPC.IDPROVEEDOR = PRO.IDPROVEEDOR INNER JOIN ")
        strSQL.Append(" SAB_UACI_RECEPCIONOFERTAS AS RO ON C.IDESTABLECIMIENTO = RO.IDESTABLECIMIENTO AND C.IDPROVEEDOR = RO.IDPROVEEDOR AND ")
        strSQL.Append(" PC.IDPROCESOCOMPRA = RO.IDPROCESOCOMPRA AND PC.IDESTABLECIMIENTO = RO.IDESTABLECIMIENTO AND ")
        strSQL.Append(" CPC.IDPROVEEDOR = RO.IDPROVEEDOR AND PRO.IDPROVEEDOR = RO.IDPROVEEDOR INNER JOIN ")
        strSQL.Append(" SAB_UACI_GARANTIASCONTRATOS AS GC ON C.IDESTABLECIMIENTO = GC.IDESTABLECIMIENTO AND C.IDPROVEEDOR = GC.IDPROVEEDOR AND ")
        strSQL.Append(" C.IDCONTRATO = GC.IDCONTRATO INNER JOIN ")
        strSQL.Append(" SAB_CAT_ESTADOSGARANTIAS AS EG ON GC.IDESTADOGARANTIA = EG.IDESTADOGARANTIA INNER JOIN ")
        strSQL.Append(" SAB_CAT_TIPOGARANTIAS AS TG ON GC.IDTIPOGARANTIA = TG.IDTIPOGARANTIA ")
        strSQL.Append(" WHERE (C.IDPROVEEDOR = @IDPROVEEDOR) AND (C.IDESTABLECIMIENTO = @IDESTABLECIMIENTO) ")
        strSQL.Append(" ORDER BY PC.IDPROCESOCOMPRA, C.NUMEROCONTRATO, GC.NUMEROGARANTIA ")

        Dim args(2) As SqlParameter
        args(0) = New SqlParameter("@IDESTABLECIMIENTO", SqlDbType.Int)
        args(0).Value = IDESTABLECIMIENTO
        args(1) = New SqlParameter("@IDPROVEEDOR", SqlDbType.Int)
        args(1).Value = IDPROVEEDOR

        Dim ds As DataSet
        ds = SqlHelper.ExecuteDataset(Me.cnnStr, CommandType.Text, strSQL.ToString(), args)

        Return ds

    End Function

    Public Function ObtenerDataSetBusquedaContrato(ByVal IDESTABLECIMIENTO As Int32, ByVal CONTRATO As String) As DataSet

        Dim strSQL As New Text.StringBuilder
        strSQL.Append("SELECT SAB_UACI_PROCESOCOMPRAS.IDPROCESOCOMPRA, SAB_UACI_CONTRATOS.IDPROVEEDOR, ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA.IDCONTRATO, SAB_UACI_PROCESOCOMPRAS.CODIGOLICITACION, ")
        strSQL.Append(" SAB_UACI_RECEPCIONOFERTAS.ORDENLLEGADA, SAB_UACI_CONTRATOS.NUMEROCONTRATO, SAB_CAT_PROVEEDORES.NOMBRE, ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDESTABLECIMIENTO ")
        strSQL.Append(" FROM SAB_UACI_CONTRATOS INNER JOIN ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS ON SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = SAB_UACI_PROCESOCOMPRAS.IDESTABLECIMIENTO INNER JOIN ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA ON ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDPROVEEDOR = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDCONTRATO = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDCONTRATO AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDPROCESOCOMPRA = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROCESOCOMPRA AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDESTABLECIMIENTO = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDESTABLECIMIENTO INNER JOIN ")
        strSQL.Append(" SAB_CAT_PROVEEDORES ON SAB_UACI_CONTRATOS.IDPROVEEDOR = SAB_CAT_PROVEEDORES.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROVEEDOR = SAB_CAT_PROVEEDORES.IDPROVEEDOR INNER JOIN ")
        strSQL.Append(" SAB_UACI_RECEPCIONOFERTAS ON SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = SAB_UACI_RECEPCIONOFERTAS.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDPROVEEDOR = SAB_UACI_RECEPCIONOFERTAS.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDPROCESOCOMPRA = SAB_UACI_RECEPCIONOFERTAS.IDPROCESOCOMPRA AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.idestablecimiento = SAB_UACI_RECEPCIONOFERTAS.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROVEEDOR = SAB_UACI_RECEPCIONOFERTAS.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_CAT_PROVEEDORES.IDPROVEEDOR = SAB_UACI_RECEPCIONOFERTAS.IDPROVEEDOR ")
        strSQL.Append(" WHERE (SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = @IDESTABLECIMIENTO) AND ")
        strSQL.Append("   (SAB_UACI_CONTRATOS.NUMEROCONTRATO  LIKE '%' + @CONTRATO + '%') ")

        Dim args(2) As SqlParameter
        args(0) = New SqlParameter("@IDESTABLECIMIENTO", SqlDbType.Int)
        args(0).Value = IDESTABLECIMIENTO
        args(1) = New SqlParameter("@CONTRATO", SqlDbType.VarChar)
        args(1).Value = CONTRATO

        Dim ds As DataSet
        ds = SqlHelper.ExecuteDataset(Me.cnnStr, CommandType.Text, strSQL.ToString(), args)

        Return ds

    End Function

    Public Function ObtenerDataSetBusquedaTipoGarantia(ByVal IDESTABLECIMIENTO As Int32, ByVal IDTIPOGARANTIA As Int32) As DataSet

        Dim strSQL As New Text.StringBuilder
        strSQL.Append(" SELECT SAB_UACI_PROCESOCOMPRAS.IDPROCESOCOMPRA, SAB_UACI_CONTRATOS.IDPROVEEDOR, ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA.IDCONTRATO, SAB_UACI_GARANTIASCONTRATOS.IDTIPOGARANTIA, ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDESTABLECIMIENTO, SAB_UACI_PROCESOCOMPRAS.CODIGOLICITACION, ")
        strSQL.Append(" SAB_UACI_RECEPCIONOFERTAS.ORDENLLEGADA, SAB_UACI_CONTRATOS.NUMEROCONTRATO, SAB_CAT_PROVEEDORES.NOMBRE, ")
        strSQL.Append(" SAB_UACI_GARANTIASCONTRATOS.NUMEROGARANTIA, CONVERT(varchar(10),SAB_UACI_GARANTIASCONTRATOS.FECHAVENCIMIENTO,103) as FECHAVENCIMIENTO, ")
        strSQL.Append(" SAB_CAT_TIPOGARANTIAS.NOMBRE AS tipogarantia ")
        strSQL.Append(" FROM SAB_UACI_CONTRATOS INNER JOIN ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS ON SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = SAB_UACI_PROCESOCOMPRAS.IDESTABLECIMIENTO INNER JOIN ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA ON ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDPROVEEDOR = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDCONTRATO = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDCONTRATO AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDPROCESOCOMPRA = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROCESOCOMPRA AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDESTABLECIMIENTO = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDESTABLECIMIENTO INNER JOIN ")
        strSQL.Append(" SAB_CAT_PROVEEDORES ON SAB_UACI_CONTRATOS.IDPROVEEDOR = SAB_CAT_PROVEEDORES.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROVEEDOR = SAB_CAT_PROVEEDORES.IDPROVEEDOR INNER JOIN ")
        strSQL.Append(" SAB_UACI_RECEPCIONOFERTAS ON SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = SAB_UACI_RECEPCIONOFERTAS.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDPROVEEDOR = SAB_UACI_RECEPCIONOFERTAS.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDPROCESOCOMPRA = SAB_UACI_RECEPCIONOFERTAS.IDPROCESOCOMPRA AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDESTABLECIMIENTO = SAB_UACI_RECEPCIONOFERTAS.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROVEEDOR = SAB_UACI_RECEPCIONOFERTAS.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_CAT_PROVEEDORES.IDPROVEEDOR = SAB_UACI_RECEPCIONOFERTAS.IDPROVEEDOR INNER JOIN ")
        strSQL.Append(" SAB_UACI_GARANTIASCONTRATOS ON SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = SAB_UACI_GARANTIASCONTRATOS.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDPROVEEDOR = SAB_UACI_GARANTIASCONTRATOS.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDCONTRATO = SAB_UACI_GARANTIASCONTRATOS.IDCONTRATO AND ")
        strSQL.Append(" SAB_CAT_PROVEEDORES.IDPROVEEDOR = SAB_UACI_GARANTIASCONTRATOS.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROVEEDOR = SAB_UACI_GARANTIASCONTRATOS.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_RECEPCIONOFERTAS.IDPROVEEDOR = SAB_UACI_GARANTIASCONTRATOS.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDESTABLECIMIENTO = SAB_UACI_GARANTIASCONTRATOS.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_RECEPCIONOFERTAS.IDESTABLECIMIENTO = SAB_UACI_GARANTIASCONTRATOS.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA.IDCONTRATO = SAB_UACI_GARANTIASCONTRATOS.IDCONTRATO INNER JOIN ")
        strSQL.Append(" SAB_CAT_TIPOGARANTIAS ON SAB_UACI_GARANTIASCONTRATOS.IDTIPOGARANTIA = SAB_CAT_TIPOGARANTIAS.IDTIPOGARANTIA ")
        strSQL.Append(" WHERE (SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = @IDESTABLECIMIENTO) AND (SAB_UACI_GARANTIASCONTRATOS.IDTIPOGARANTIA = @IDTIPOGARANTIA) ")

        Dim args(2) As SqlParameter
        args(0) = New SqlParameter("@IDESTABLECIMIENTO", SqlDbType.Int)
        args(0).Value = IDESTABLECIMIENTO
        args(1) = New SqlParameter("@IDTIPOGARANTIA", SqlDbType.Int)
        args(1).Value = IDTIPOGARANTIA

        Dim ds As DataSet
        ds = SqlHelper.ExecuteDataset(Me.cnnStr, CommandType.Text, strSQL.ToString(), args)

        Return ds

    End Function

    Public Function obtenerDsRptTipoGarantia(ByVal IDESTABLECIMIENTO As Integer, ByVal IDTIPOGARANTIA As Integer) As DataSet

        Dim strSQL As New Text.StringBuilder
        strSQL.Append(" SELECT PC.IDPROCESOCOMPRA, C.IDPROVEEDOR, CPC.IDCONTRATO, RO.ORDENLLEGADA, C.IDESTABLECIMIENTO, GC.IDTIPOGARANTIA, ")
        strSQL.Append(" CONVERT(VARCHAR(10), GC.FECHARECEPCION, 103) AS FECHARECEPCION, GC.NUMEROGARANTIA, CONVERT(VARCHAR(10), ")
        strSQL.Append(" GC.FECHAVENCIMIENTO, 103) AS FECHAVENCIMIENTO, GC.VIGENCIA, GC.MONTO, GC.ASEGURADORA, PC.CODIGOLICITACION, ")
        strSQL.Append(" PC.NUMERORESOLUCION, C.NUMEROCONTRATO, PRO.NOMBRE AS PROVEEDOR, EG.DESCRIPCION AS ESTADO, CONVERT(VARCHAR(10), ")
        strSQL.Append(" GC.FECHAEFECTIVA, 103) AS FECHAEFECTIVA, CONVERT(VARCHAR(10), GC.FECHADEVOLUCION, 103) AS FECHADEVOLUCION, ")
        strSQL.Append(" CONVERT(VARCHAR(10), dateadd(mm,36,GC.FECHAVENCIMIENTO), 103) AS FECHAEXPIRACION, TG.NOMBRE AS TIPO ")
        strSQL.Append(" FROM SAB_UACI_CONTRATOS AS C INNER JOIN ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS AS PC ON C.IDESTABLECIMIENTO = PC.IDESTABLECIMIENTO INNER JOIN ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA AS CPC ON C.IDESTABLECIMIENTO = CPC.IDESTABLECIMIENTO AND ")
        strSQL.Append(" C.IDPROVEEDOR = CPC.IDPROVEEDOR AND C.IDCONTRATO = CPC.IDCONTRATO AND PC.IDPROCESOCOMPRA = CPC.IDPROCESOCOMPRA AND ")
        strSQL.Append(" PC.IDESTABLECIMIENTO = CPC.IDESTABLECIMIENTO INNER JOIN ")
        strSQL.Append(" SAB_CAT_PROVEEDORES AS PRO ON C.IDPROVEEDOR = PRO.IDPROVEEDOR AND CPC.IDPROVEEDOR = PRO.IDPROVEEDOR INNER JOIN ")
        strSQL.Append(" SAB_UACI_RECEPCIONOFERTAS AS RO ON C.IDESTABLECIMIENTO = RO.IDESTABLECIMIENTO AND C.IDPROVEEDOR = RO.IDPROVEEDOR AND ")
        strSQL.Append(" PC.IDPROCESOCOMPRA = RO.IDPROCESOCOMPRA AND PC.IDESTABLECIMIENTO = RO.IDESTABLECIMIENTO AND ")
        strSQL.Append(" CPC.IDPROVEEDOR = RO.IDPROVEEDOR AND PRO.IDPROVEEDOR = RO.IDPROVEEDOR INNER JOIN ")
        strSQL.Append(" SAB_UACI_GARANTIASCONTRATOS AS GC ON C.IDESTABLECIMIENTO = GC.IDESTABLECIMIENTO AND C.IDPROVEEDOR = GC.IDPROVEEDOR AND ")
        strSQL.Append(" C.IDCONTRATO = GC.IDCONTRATO INNER JOIN ")
        strSQL.Append(" SAB_CAT_ESTADOSGARANTIAS AS EG ON GC.IDESTADOGARANTIA = EG.IDESTADOGARANTIA INNER JOIN ")
        strSQL.Append(" SAB_CAT_TIPOGARANTIAS AS TG ON GC.IDTIPOGARANTIA = TG.IDTIPOGARANTIA ")
        strSQL.Append(" WHERE (C.IDESTABLECIMIENTO = @IDESTABLECIMIENTO) AND (GC.IDTIPOGARANTIA = @IDTIPOGARANTIA) ")
        strSQL.Append(" ORDER BY PC.IDPROCESOCOMPRA, C.NUMEROCONTRATO, GC.NUMEROGARANTIA ")

        Dim args(2) As SqlParameter
        args(0) = New SqlParameter("@IDESTABLECIMIENTO", SqlDbType.Int)
        args(0).Value = IDESTABLECIMIENTO
        args(1) = New SqlParameter("@IDTIPOGARANTIA", SqlDbType.Int)
        args(1).Value = IDTIPOGARANTIA

        Dim ds As DataSet
        ds = SqlHelper.ExecuteDataset(Me.cnnStr, CommandType.Text, strSQL.ToString(), args)

        Return ds

    End Function

    Public Function ObtenerDataSetBusquedaNumeroGarantia(ByVal IDESTABLECIMIENTO As Int32, ByVal NUMEROGARANTIA As String) As DataSet

        Dim strSQL As New Text.StringBuilder
        strSQL.Append(" SELECT SAB_UACI_PROCESOCOMPRAS.IDPROCESOCOMPRA, SAB_UACI_CONTRATOS.IDPROVEEDOR, ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA.IDCONTRATO, SAB_UACI_GARANTIASCONTRATOS.IDTIPOGARANTIA, ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDESTABLECIMIENTO, SAB_UACI_PROCESOCOMPRAS.CODIGOLICITACION, ")
        strSQL.Append(" SAB_UACI_RECEPCIONOFERTAS.ORDENLLEGADA, SAB_UACI_CONTRATOS.NUMEROCONTRATO, SAB_CAT_PROVEEDORES.NOMBRE, ")
        strSQL.Append(" SAB_UACI_GARANTIASCONTRATOS.NUMEROGARANTIA, CONVERT(varchar(10),SAB_UACI_GARANTIASCONTRATOS.FECHAVENCIMIENTO,103) as FECHAVENCIMIENTO, ")
        strSQL.Append(" SAB_CAT_TIPOGARANTIAS.NOMBRE AS tipogarantia ")
        strSQL.Append(" FROM SAB_UACI_CONTRATOS INNER JOIN ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS ON SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = SAB_UACI_PROCESOCOMPRAS.IDESTABLECIMIENTO INNER JOIN ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA ON ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDPROVEEDOR = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDCONTRATO = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDCONTRATO AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDPROCESOCOMPRA = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROCESOCOMPRA AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDESTABLECIMIENTO = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDESTABLECIMIENTO INNER JOIN ")
        strSQL.Append(" SAB_CAT_PROVEEDORES ON SAB_UACI_CONTRATOS.IDPROVEEDOR = SAB_CAT_PROVEEDORES.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROVEEDOR = SAB_CAT_PROVEEDORES.IDPROVEEDOR INNER JOIN ")
        strSQL.Append(" SAB_UACI_RECEPCIONOFERTAS ON SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = SAB_UACI_RECEPCIONOFERTAS.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDPROVEEDOR = SAB_UACI_RECEPCIONOFERTAS.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDPROCESOCOMPRA = SAB_UACI_RECEPCIONOFERTAS.IDPROCESOCOMPRA AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDESTABLECIMIENTO = SAB_UACI_RECEPCIONOFERTAS.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROVEEDOR = SAB_UACI_RECEPCIONOFERTAS.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_CAT_PROVEEDORES.IDPROVEEDOR = SAB_UACI_RECEPCIONOFERTAS.IDPROVEEDOR INNER JOIN ")
        strSQL.Append(" SAB_UACI_GARANTIASCONTRATOS ON SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = SAB_UACI_GARANTIASCONTRATOS.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDPROVEEDOR = SAB_UACI_GARANTIASCONTRATOS.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDCONTRATO = SAB_UACI_GARANTIASCONTRATOS.IDCONTRATO AND ")
        strSQL.Append(" SAB_CAT_PROVEEDORES.IDPROVEEDOR = SAB_UACI_GARANTIASCONTRATOS.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROVEEDOR = SAB_UACI_GARANTIASCONTRATOS.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_RECEPCIONOFERTAS.IDPROVEEDOR = SAB_UACI_GARANTIASCONTRATOS.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDESTABLECIMIENTO = SAB_UACI_GARANTIASCONTRATOS.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_RECEPCIONOFERTAS.IDESTABLECIMIENTO = SAB_UACI_GARANTIASCONTRATOS.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA.IDCONTRATO = SAB_UACI_GARANTIASCONTRATOS.IDCONTRATO INNER JOIN ")
        strSQL.Append(" SAB_CAT_TIPOGARANTIAS ON SAB_UACI_GARANTIASCONTRATOS.IDTIPOGARANTIA = SAB_CAT_TIPOGARANTIAS.IDTIPOGARANTIA ")
        strSQL.Append(" WHERE (SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = @IDESTABLECIMIENTO) AND (SAB_UACI_GARANTIASCONTRATOS.NUMEROGARANTIA = @NUMEROGARANTIA) ")

        Dim args(2) As SqlParameter
        args(0) = New SqlParameter("@IDESTABLECIMIENTO", SqlDbType.Int)
        args(0).Value = IDESTABLECIMIENTO
        args(1) = New SqlParameter("@NUMEROGARANTIA", SqlDbType.VarChar)
        args(1).Value = NUMEROGARANTIA

        Dim ds As DataSet
        ds = SqlHelper.ExecuteDataset(Me.cnnStr, CommandType.Text, strSQL.ToString(), args)

        Return ds

    End Function

    Public Function ObtenerDataSetBusquedaFechaVencimiento(ByVal IDESTABLECIMIENTO As Int32, ByVal FECHAVENCIMIENTO As Date) As DataSet

        Dim strSQL As New Text.StringBuilder
        strSQL.Append(" SELECT SAB_UACI_PROCESOCOMPRAS.IDPROCESOCOMPRA, SAB_UACI_CONTRATOS.IDPROVEEDOR, ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA.IDCONTRATO, SAB_UACI_GARANTIASCONTRATOS.IDTIPOGARANTIA, ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDESTABLECIMIENTO, SAB_UACI_PROCESOCOMPRAS.CODIGOLICITACION, ")
        strSQL.Append(" SAB_UACI_RECEPCIONOFERTAS.ORDENLLEGADA, SAB_UACI_CONTRATOS.NUMEROCONTRATO, SAB_CAT_PROVEEDORES.NOMBRE, ")
        strSQL.Append(" SAB_UACI_GARANTIASCONTRATOS.NUMEROGARANTIA, CONVERT(varchar(10),SAB_UACI_GARANTIASCONTRATOS.FECHAVENCIMIENTO,103) as FECHAVENCIMIENTO, ")
        strSQL.Append(" SAB_CAT_TIPOGARANTIAS.NOMBRE AS tipogarantia ")
        strSQL.Append(" FROM SAB_UACI_CONTRATOS INNER JOIN ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS ON SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = SAB_UACI_PROCESOCOMPRAS.IDESTABLECIMIENTO INNER JOIN ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA ON ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDPROVEEDOR = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDCONTRATO = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDCONTRATO AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDPROCESOCOMPRA = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROCESOCOMPRA AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDESTABLECIMIENTO = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDESTABLECIMIENTO INNER JOIN ")
        strSQL.Append(" SAB_CAT_PROVEEDORES ON SAB_UACI_CONTRATOS.IDPROVEEDOR = SAB_CAT_PROVEEDORES.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROVEEDOR = SAB_CAT_PROVEEDORES.IDPROVEEDOR INNER JOIN ")
        strSQL.Append(" SAB_UACI_RECEPCIONOFERTAS ON SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = SAB_UACI_RECEPCIONOFERTAS.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDPROVEEDOR = SAB_UACI_RECEPCIONOFERTAS.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDPROCESOCOMPRA = SAB_UACI_RECEPCIONOFERTAS.IDPROCESOCOMPRA AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDESTABLECIMIENTO = SAB_UACI_RECEPCIONOFERTAS.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROVEEDOR = SAB_UACI_RECEPCIONOFERTAS.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_CAT_PROVEEDORES.IDPROVEEDOR = SAB_UACI_RECEPCIONOFERTAS.IDPROVEEDOR INNER JOIN ")
        strSQL.Append(" SAB_UACI_GARANTIASCONTRATOS ON SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = SAB_UACI_GARANTIASCONTRATOS.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDPROVEEDOR = SAB_UACI_GARANTIASCONTRATOS.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDCONTRATO = SAB_UACI_GARANTIASCONTRATOS.IDCONTRATO AND ")
        strSQL.Append(" SAB_CAT_PROVEEDORES.IDPROVEEDOR = SAB_UACI_GARANTIASCONTRATOS.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROVEEDOR = SAB_UACI_GARANTIASCONTRATOS.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_RECEPCIONOFERTAS.IDPROVEEDOR = SAB_UACI_GARANTIASCONTRATOS.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDESTABLECIMIENTO = SAB_UACI_GARANTIASCONTRATOS.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_RECEPCIONOFERTAS.IDESTABLECIMIENTO = SAB_UACI_GARANTIASCONTRATOS.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA.IDCONTRATO = SAB_UACI_GARANTIASCONTRATOS.IDCONTRATO INNER JOIN ")
        strSQL.Append(" SAB_CAT_TIPOGARANTIAS ON SAB_UACI_GARANTIASCONTRATOS.IDTIPOGARANTIA = SAB_CAT_TIPOGARANTIAS.IDTIPOGARANTIA ")
        strSQL.Append(" WHERE (SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = @IDESTABLECIMIENTO) AND (SAB_UACI_GARANTIASCONTRATOS.FECHAVENCIMIENTO <= @FECHAVENCIMIENTO) ")

        Dim args(2) As SqlParameter
        args(0) = New SqlParameter("@IDESTABLECIMIENTO", SqlDbType.Int)
        args(0).Value = IDESTABLECIMIENTO
        args(1) = New SqlParameter("@FECHAVENCIMIENTO", SqlDbType.DateTime)
        args(1).Value = FECHAVENCIMIENTO

        Dim ds As DataSet
        ds = SqlHelper.ExecuteDataset(Me.cnnStr, CommandType.Text, strSQL.ToString(), args)

        Return ds

    End Function

    Public Function obtenerDsRptFechaVencimiento(ByVal IDESTABLECIMIENTO As Int32, ByVal FECHAVENCIMIENTO As Date) As DataSet

        Dim strSQL As New Text.StringBuilder
        strSQL.Append(" SELECT PC.IDPROCESOCOMPRA, C.IDPROVEEDOR, CPC.IDCONTRATO, RO.ORDENLLEGADA, C.IDESTABLECIMIENTO, GC.IDTIPOGARANTIA, ")
        strSQL.Append(" CONVERT(VARCHAR(10), GC.FECHARECEPCION, 103) AS FECHARECEPCION, GC.NUMEROGARANTIA, CONVERT(VARCHAR(10), ")
        strSQL.Append(" GC.FECHAVENCIMIENTO, 103) AS FECHAVENCIMIENTO, GC.VIGENCIA, GC.MONTO, GC.ASEGURADORA, PC.CODIGOLICITACION, ")
        strSQL.Append(" PC.NUMERORESOLUCION, C.NUMEROCONTRATO, PRO.NOMBRE AS PROVEEDOR, EG.DESCRIPCION AS ESTADO, CONVERT(VARCHAR(10), ")
        strSQL.Append(" GC.FECHAEFECTIVA, 103) AS FECHAEFECTIVA, CONVERT(VARCHAR(10), GC.FECHADEVOLUCION, 103) AS FECHADEVOLUCION, ")
        strSQL.Append(" CONVERT(VARCHAR(10), dateadd(mm,36,GC.FECHAVENCIMIENTO), 103) AS FECHAEXPIRACION, TG.NOMBRE AS TIPO ")
        strSQL.Append(" FROM SAB_UACI_CONTRATOS AS C INNER JOIN ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS AS PC ON C.IDESTABLECIMIENTO = PC.IDESTABLECIMIENTO INNER JOIN ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA AS CPC ON C.IDESTABLECIMIENTO = CPC.IDESTABLECIMIENTO AND ")
        strSQL.Append(" C.IDPROVEEDOR = CPC.IDPROVEEDOR AND C.IDCONTRATO = CPC.IDCONTRATO AND PC.IDPROCESOCOMPRA = CPC.IDPROCESOCOMPRA AND ")
        strSQL.Append(" PC.IDESTABLECIMIENTO = CPC.IDESTABLECIMIENTO INNER JOIN ")
        strSQL.Append(" SAB_CAT_PROVEEDORES AS PRO ON C.IDPROVEEDOR = PRO.IDPROVEEDOR AND CPC.IDPROVEEDOR = PRO.IDPROVEEDOR INNER JOIN ")
        strSQL.Append(" SAB_UACI_RECEPCIONOFERTAS AS RO ON C.IDESTABLECIMIENTO = RO.IDESTABLECIMIENTO AND C.IDPROVEEDOR = RO.IDPROVEEDOR AND ")
        strSQL.Append(" PC.IDPROCESOCOMPRA = RO.IDPROCESOCOMPRA AND PC.IDESTABLECIMIENTO = RO.IDESTABLECIMIENTO AND ")
        strSQL.Append(" CPC.IDPROVEEDOR = RO.IDPROVEEDOR AND PRO.IDPROVEEDOR = RO.IDPROVEEDOR INNER JOIN ")
        strSQL.Append(" SAB_UACI_GARANTIASCONTRATOS AS GC ON C.IDESTABLECIMIENTO = GC.IDESTABLECIMIENTO AND C.IDPROVEEDOR = GC.IDPROVEEDOR AND ")
        strSQL.Append(" C.IDCONTRATO = GC.IDCONTRATO INNER JOIN ")
        strSQL.Append(" SAB_CAT_ESTADOSGARANTIAS AS EG ON GC.IDESTADOGARANTIA = EG.IDESTADOGARANTIA INNER JOIN ")
        strSQL.Append(" SAB_CAT_TIPOGARANTIAS AS TG ON GC.IDTIPOGARANTIA = TG.IDTIPOGARANTIA ")
        strSQL.Append(" WHERE (C.IDESTABLECIMIENTO = @IDESTABLECIMIENTO) AND (GC.FECHAVENCIMIENTO <= @FECHAVENCIMIENTO) ")
        strSQL.Append(" ORDER BY PC.IDPROCESOCOMPRA, C.NUMEROCONTRATO, GC.NUMEROGARANTIA ")

        Dim args(2) As SqlParameter
        args(0) = New SqlParameter("@IDESTABLECIMIENTO", SqlDbType.Int)
        args(0).Value = IDESTABLECIMIENTO
        args(1) = New SqlParameter("@FECHAVENCIMIENTO", SqlDbType.DateTime)
        args(1).Value = FECHAVENCIMIENTO

        Dim ds As DataSet
        ds = SqlHelper.ExecuteDataset(Me.cnnStr, CommandType.Text, strSQL.ToString(), args)

        Return ds

    End Function

    ''' <summary>
    ''' Obtener las garantias por contrato
    ''' </summary>
    ''' <param name="IDESTABLECIMIENTO"></param> identificador del establecimiento
    ''' <param name="IDCONTRATO"></param> identificador del contrato
    ''' <param name="IDPROVEEDOR"></param> identificador del proveedor
    ''' <returns>
    ''' dataset con la informacion solicitada
    ''' </returns>
    ''' <remarks>
    ''' <list type="bullet">
    ''' <item><description>SAB_UACI_GARANTIASCONTRATOS</description></item>
    ''' <item><description>SAB_CAT_TIPOGARANTIAS</description></item>
    ''' <item><description>SAB_CAT_ESTADOSGARANTIAS</description></item>
    ''' <item><description>SAB_UACI_GARANTIASCONTRATOS</description></item>
    ''' </list> 
    ''' </remarks>
    ''' <history>
    '''     [Autor: Yessenia Henriquez]      Creado
    ''' </history>
    Public Function obtenerGarantiasXContrato(ByVal IDESTABLECIMIENTO As Int32, ByVal IDCONTRATO As Int32, ByVal IDPROVEEDOR As Int32) As DataSet

        Dim strSQL As New Text.StringBuilder
        strSQL.Append("SELECT SAB_UACI_GARANTIASCONTRATOS.IDESTABLECIMIENTO, SAB_UACI_GARANTIASCONTRATOS.IDPROVEEDOR, ")
        strSQL.Append("SAB_UACI_GARANTIASCONTRATOS.IDCONTRATO, SAB_UACI_GARANTIASCONTRATOS.IDGARANTIACONTRATO, SAB_UACI_GARANTIASCONTRATOS.IDMODIFICATIVA, ")
        strSQL.Append("SAB_UACI_GARANTIASCONTRATOS.NUMEROGARANTIA, ")
        strSQL.Append("SAB_UACI_GARANTIASCONTRATOS.FECHAENTREGA, SAB_UACI_GARANTIASCONTRATOS.FECHARECEPCION, ")
        strSQL.Append("SAB_UACI_GARANTIASCONTRATOS.MONTO, SAB_UACI_GARANTIASCONTRATOS.VIGENCIA, SAB_UACI_GARANTIASCONTRATOS.FECHAVENCIMIENTO, ")
        strSQL.Append("SAB_UACI_GARANTIASCONTRATOS.ASEGURADORA, SAB_UACI_GARANTIASCONTRATOS.FECHAEFECTIVA, ")
        strSQL.Append("SAB_UACI_GARANTIASCONTRATOS.JUSTIFICACIONEFECTIVA, SAB_UACI_GARANTIASCONTRATOS.FECHADEVOLUCION, ")
        strSQL.Append("SAB_UACI_GARANTIASCONTRATOS.JUSTIFICACIONDEVOLUCION, SAB_CAT_TIPOGARANTIAS.NOMBRE AS TIPOGARANTIA, ")
        strSQL.Append("SAB_CAT_ESTADOSGARANTIAS.DESCRIPCION AS ESTADOGARANTIA, SAB_UACI_GARANTIASCONTRATOS.IDTIPOGARANTIA ")
        strSQL.Append("FROM SAB_UACI_GARANTIASCONTRATOS INNER JOIN ")
        strSQL.Append("SAB_CAT_TIPOGARANTIAS ON SAB_UACI_GARANTIASCONTRATOS.IDTIPOGARANTIA = SAB_CAT_TIPOGARANTIAS.IDTIPOGARANTIA INNER JOIN ")
        strSQL.Append("SAB_CAT_ESTADOSGARANTIAS ON SAB_UACI_GARANTIASCONTRATOS.IDESTADOGARANTIA = SAB_CAT_ESTADOSGARANTIAS.IDESTADOGARANTIA ")
        strSQL.Append("WHERE SAB_UACI_GARANTIASCONTRATOS.IDESTABLECIMIENTO = @IDESTABLECIMIENTO ")
        strSQL.Append("AND SAB_UACI_GARANTIASCONTRATOS.IDCONTRATO = @IDCONTRATO ")
        strSQL.Append("AND SAB_UACI_GARANTIASCONTRATOS.IDPROVEEDOR = @IDPROVEEDOR ")

        Dim args(2) As SqlParameter
        args(0) = New SqlParameter("@IDESTABLECIMIENTO", SqlDbType.Int)
        args(0).Value = IDESTABLECIMIENTO
        args(1) = New SqlParameter("@IDCONTRATO", SqlDbType.Int)
        args(1).Value = IDCONTRATO
        args(2) = New SqlParameter("@IDPROVEEDOR", SqlDbType.Int)
        args(2).Value = IDPROVEEDOR

        Dim ds As DataSet
        ds = SqlHelper.ExecuteDataset(Me.cnnStr, CommandType.Text, strSQL.ToString(), args)

        Return ds

    End Function

    Public Function obtenerDatasetGarantiasXContrato(ByVal IDESTABLECIMIENTO As Int32, ByVal IDCONTRATO As Int32, ByVal IDPROVEEDOR As Integer) As DataSet

        Dim strSQL As New Text.StringBuilder
        strSQL.Append(" SELECT SAB_UACI_GARANTIASCONTRATOS.IDESTABLECIMIENTO, SAB_UACI_GARANTIASCONTRATOS.IDPROVEEDOR, ")
        strSQL.Append(" SAB_UACI_GARANTIASCONTRATOS.IDCONTRATO, SAB_UACI_GARANTIASCONTRATOS.IDTIPOGARANTIA, SAB_CAT_TIPOGARANTIAS.NOMBRE, ")
        strSQL.Append(" convert(varchar(10), SAB_UACI_GARANTIASCONTRATOS.FECHAENTREGA, 103) as FECHAENTREGA, convert(varchar(10), SAB_UACI_GARANTIASCONTRATOS.FECHARECEPCION,103) as FECHARECEPCION, ")
        strSQL.Append(" convert(varchar(10), SAB_UACI_GARANTIASCONTRATOS.FECHAVENCIMIENTO,103) as FECHAVENCIMIENTO, ")
        strSQL.Append(" SAB_UACI_GARANTIASCONTRATOS.MONTO, SAB_UACI_GARANTIASCONTRATOS.VIGENCIA, SAB_CAT_ESTADOSGARANTIAS.DESCRIPCION, SAB_UACI_GARANTIASCONTRATOS.IDGARANTIACONTRATO ")
        strSQL.Append(" FROM SAB_UACI_GARANTIASCONTRATOS INNER JOIN ")
        strSQL.Append(" SAB_CAT_TIPOGARANTIAS ON SAB_UACI_GARANTIASCONTRATOS.IDTIPOGARANTIA = SAB_CAT_TIPOGARANTIAS.IDTIPOGARANTIA INNER JOIN ")
        strSQL.Append(" SAB_CAT_ESTADOSGARANTIAS ON ")
        strSQL.Append(" SAB_UACI_GARANTIASCONTRATOS.IDESTADOGARANTIA = SAB_CAT_ESTADOSGARANTIAS.IDESTADOGARANTIA ")
        strSQL.Append(" WHERE (SAB_UACI_GARANTIASCONTRATOS.IDESTABLECIMIENTO = @IDESTABLECIMIENTO) AND ")
        strSQL.Append("  (SAB_UACI_GARANTIASCONTRATOS.IDCONTRATO = @IDCONTRATO) AND (SAB_UACI_GARANTIASCONTRATOS.IDPROVEEDOR = @IDPROVEEDOR)")

        Dim args(3) As SqlParameter
        args(0) = New SqlParameter("@IDESTABLECIMIENTO", SqlDbType.Int)
        args(0).Value = IDESTABLECIMIENTO
        args(1) = New SqlParameter("@IDCONTRATO", SqlDbType.Int)
        args(1).Value = IDCONTRATO
        args(2) = New SqlParameter("@IDPROVEEDOR", SqlDbType.Int)
        args(2).Value = IDPROVEEDOR

        Dim ds As DataSet
        ds = SqlHelper.ExecuteDataset(Me.cnnStr, CommandType.Text, strSQL.ToString(), args)

        Return ds

    End Function

    Public Function obtenerGARANTIAMNTTOVALOR(ByVal IDESTABLECIMIENTO As Integer, ByVal IDPROCESOCOMPRA As Integer, ByVal IDPROVEEDOR As Integer) As Decimal

        Dim strSQL As New Text.StringBuilder
        strSQL.Append("SELECT isnull(SUM(GARANTIAMTTOVALOR), 0) VALOR ")
        strSQL.Append("FROM SAB_UACI_DETALLEPROCESOCOMPRA ")
        strSQL.Append("WHERE (RENGLON IN ")
        strSQL.Append("      (SELECT RENGLON ")
        strSQL.Append("       FROM SAB_UACI_DETALLEOFERTA ")
        strSQL.Append("       WHERE (IDESTABLECIMIENTO = " & IDESTABLECIMIENTO & ") ")
        strSQL.Append("       AND (IDPROCESOCOMPRA = " & IDPROCESOCOMPRA & ") ")
        strSQL.Append("       AND (IDPROVEEDOR = " & IDPROVEEDOR & "))) ")
        strSQL.Append("AND (IDESTABLECIMIENTO = " & IDESTABLECIMIENTO & ") ")
        strSQL.Append("AND (IDPROCESOCOMPRA = " & IDPROCESOCOMPRA & ") ")

        Return SqlHelper.ExecuteScalar(Me.cnnStr, CommandType.Text, strSQL.ToString())

    End Function

    Public Function obtenerDatosGarantia(ByVal IDESTABLECIMIENTO As Integer, ByVal IDPROVEEDOR As Integer, ByVal IDCONTRATO As Integer, ByVal IDTIPOGARANTIA As Integer) As DataSet

        Dim strSQL As New Text.StringBuilder
        strSQL.Append(" SELECT IDESTABLECIMIENTO, IDPROVEEDOR, IDCONTRATO, IDTIPOGARANTIA, MONTO, VIGENCIA, PORCENTAJE ")
        strSQL.Append(" FROM SAB_UACI_GARANTIASCONTRATOS ")
        strSQL.Append(" WHERE (IDESTABLECIMIENTO = " & IDESTABLECIMIENTO & ") AND (IDPROVEEDOR = " & IDPROVEEDOR & ") AND (IDCONTRATO = " & IDCONTRATO & ") AND (IDTIPOGARANTIA = " & IDTIPOGARANTIA & ") ")

        Return SqlHelper.ExecuteDataset(Me.cnnStr, CommandType.Text, strSQL.ToString())

    End Function

    Public Function obtenerEncabezadoGarantia(ByVal IDESTABLECIMIENTO As Integer, ByVal IDPROVEEDOR As Integer, ByVal IDCONTRATO As Integer, ByVal IDTIPOGARANTIA As Integer, ByVal IDGARANTIACONTRATO As Integer) As DataSet

        Dim strSQL As New Text.StringBuilder
        strSQL.Append(" SELECT SAB_CAT_PROVEEDORES.NOMBRE AS PROVEEDOR, SAB_UACI_PROCESOCOMPRAS.CODIGOLICITACION AS PROCESOCOMPRA, ")
        strSQL.Append(" SAB_UACI_CONTRATOS.MONTOCONTRATO, SAB_UACI_PROCESOCOMPRAS.NUMERORESOLUCION, SAB_UACI_CONTRATOS.NUMEROCONTRATO, ")
        strSQL.Append(" SAB_CAT_ESTADOSGARANTIAS.DESCRIPCION AS ESTADO, SAB_CAT_ESTADOSGARANTIAS.IDESTADOGARANTIA, ")
        strSQL.Append(" CASE WHEN ISNULL(SAB_UACI_CONTRATOS.TIPOPERSONA, 'N') = 'N' THEN 'Natural' ELSE 'Jurídica' END AS PERSONA ")
        strSQL.Append(" FROM SAB_CAT_PROVEEDORES INNER JOIN ")
        strSQL.Append(" SAB_UACI_CONTRATOS ON SAB_CAT_PROVEEDORES.IDPROVEEDOR = SAB_UACI_CONTRATOS.IDPROVEEDOR INNER JOIN ")
        strSQL.Append(" SAB_UACI_GARANTIASCONTRATOS ON SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = SAB_UACI_GARANTIASCONTRATOS.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDPROVEEDOR = SAB_UACI_GARANTIASCONTRATOS.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDCONTRATO = SAB_UACI_GARANTIASCONTRATOS.IDCONTRATO INNER JOIN ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS ON SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = SAB_UACI_PROCESOCOMPRAS.IDESTABLECIMIENTO INNER JOIN ")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA ON ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDPROVEEDOR = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDCONTRATO = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDCONTRATO AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDPROCESOCOMPRA = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROCESOCOMPRA AND ")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS.IDESTABLECIMIENTO = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_GARANTIASCONTRATOS.IDESTABLECIMIENTO = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_GARANTIASCONTRATOS.IDPROVEEDOR = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_GARANTIASCONTRATOS.IDCONTRATO = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDCONTRATO AND ")
        strSQL.Append(" SAB_CAT_PROVEEDORES.IDPROVEEDOR = SAB_UACI_CONTRATOSPROCESOCOMPRA.IDPROVEEDOR INNER JOIN ")
        strSQL.Append(" SAB_CAT_ESTADOSGARANTIAS ON SAB_UACI_GARANTIASCONTRATOS.IDESTADOGARANTIA = SAB_CAT_ESTADOSGARANTIAS.IDESTADOGARANTIA ")
        strSQL.Append(" WHERE (SAB_UACI_GARANTIASCONTRATOS.IDESTABLECIMIENTO = @IDESTABLECIMIENTO) AND ")
        strSQL.Append(" (SAB_UACI_GARANTIASCONTRATOS.IDPROVEEDOR = @IDPROVEEDOR) AND (SAB_UACI_GARANTIASCONTRATOS.IDCONTRATO = @IDCONTRATO) ")
        strSQL.Append(" AND (SAB_UACI_GARANTIASCONTRATOS.IDTIPOGARANTIA = @IDTIPOGARANTIA) AND ")
        strSQL.Append(" (SAB_UACI_GARANTIASCONTRATOS.IDGARANTIACONTRATO = @IDGARANTIACONTRATO) ")

        Dim args(4) As SqlParameter
        args(0) = New SqlParameter("@IDESTABLECIMIENTO", SqlDbType.Int)
        args(0).Value = IDESTABLECIMIENTO
        args(1) = New SqlParameter("@IDCONTRATO", SqlDbType.Int)
        args(1).Value = IDCONTRATO
        args(2) = New SqlParameter("@IDPROVEEDOR", SqlDbType.Int)
        args(2).Value = IDPROVEEDOR
        args(3) = New SqlParameter("@IDTIPOGARANTIA", SqlDbType.Int)
        args(3).Value = IDTIPOGARANTIA
        args(4) = New SqlParameter("@IDGARANTIACONTRATO", SqlDbType.Int)
        args(4).Value = IDGARANTIACONTRATO

        Dim ds As DataSet
        ds = SqlHelper.ExecuteDataset(Me.cnnStr, CommandType.Text, strSQL.ToString(), args)

        Return ds

    End Function

    Public Sub ActualizarEstadosGarantias()

        Dim strSQL As New Text.StringBuilder
        ''''' Actualizar las garantias vencidas
        strSQL.Append(" UPDATE  SAB_UACI_GARANTIASCONTRATOS ")
        strSQL.Append(" set IDESTADOGARANTIA = 3 ")
        strSQL.Append(" WHERE (FECHAVENCIMIENTO <= getdate()) ")
        strSQL.Append(" and (IDESTADOGARANTIA = 2) ")

        SqlHelper.ExecuteDataset(Me.cnnStr, CommandType.Text, strSQL.ToString())

        '' Actualizar las garantias expiradas

        Dim strSQL2 As New Text.StringBuilder
        strSQL2.Append(" UPDATE SAB_UACI_GARANTIASCONTRATOS ")
        strSQL2.Append(" SET IDESTADOGARANTIA = 5 ")
        strSQL2.Append(" WHERE (getdate() >= DateAdd(yyyy, 3, FECHAVENCIMIENTO)) ")

        SqlHelper.ExecuteDataset(Me.cnnStr, CommandType.Text, strSQL2.ToString())

    End Sub

    Public Function ObtenerDataSetRptFechaVencimiento(ByVal IDESTABLECIMIENTO As Int32, ByVal FECHAVENCIMIENTO As Date) As DataSet

        Dim strSQL As New Text.StringBuilder
        strSQL.Append(" SELECT PC.IDPROCESOCOMPRA, SAB_UACI_CONTRATOS.IDPROVEEDOR, CPC.IDCONTRATO, GC.IDTIPOGARANTIA, ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDESTABLECIMIENTO, CONVERT(VARCHAR(10), GC.FECHARECEPCION, 103) AS FECHARECEPCION, PC.CODIGOLICITACION, ")
        strSQL.Append(" RO.ORDENLLEGADA, SAB_UACI_CONTRATOS.NUMEROCONTRATO, PRO.NOMBRE AS PROVEEDOR, GC.NUMEROGARANTIA, CONVERT(varchar(10), ")
        strSQL.Append(" GC.FECHAVENCIMIENTO, 103) AS FECHAVENCIMIENTO, TG.NOMBRE AS tipogarantia, GC.VIGENCIA, GC.MONTO, GC.ASEGURADORA, ")
        strSQL.Append(" PC.NUMERORESOLUCION, SAB_CAT_ESTADOSGARANTIAS.DESCRIPCION AS ESTADO, GC.FECHAEFECTIVA, GC.FECHADEVOLUCION, ")
        strSQL.Append(" CONVERT(VARCHAR(10), DATEADD(yyyy, 3, GC.FECHAVENCIMIENTO), 103) AS FECHAEXPIRACION")
        strSQL.Append(" FROM SAB_UACI_CONTRATOS INNER JOIN")
        strSQL.Append(" SAB_UACI_PROCESOCOMPRAS AS PC ON SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = PC.IDESTABLECIMIENTO INNER JOIN")
        strSQL.Append(" SAB_UACI_CONTRATOSPROCESOCOMPRA AS CPC ON SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = CPC.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDPROVEEDOR = CPC.IDPROVEEDOR AND SAB_UACI_CONTRATOS.IDCONTRATO = CPC.IDCONTRATO AND ")
        strSQL.Append(" PC.IDPROCESOCOMPRA = CPC.IDPROCESOCOMPRA AND PC.IDESTABLECIMIENTO = CPC.IDESTABLECIMIENTO INNER JOIN")
        strSQL.Append(" SAB_CAT_PROVEEDORES AS PRO ON SAB_UACI_CONTRATOS.IDPROVEEDOR = PRO.IDPROVEEDOR AND ")
        strSQL.Append(" CPC.IDPROVEEDOR = PRO.IDPROVEEDOR INNER JOIN")
        strSQL.Append(" SAB_UACI_RECEPCIONOFERTAS AS RO ON SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = RO.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDPROVEEDOR = RO.IDPROVEEDOR AND PC.IDPROCESOCOMPRA = RO.IDPROCESOCOMPRA AND ")
        strSQL.Append(" PC.IDESTABLECIMIENTO = RO.IDESTABLECIMIENTO AND CPC.IDPROVEEDOR = RO.IDPROVEEDOR AND ")
        strSQL.Append(" PRO.IDPROVEEDOR = RO.IDPROVEEDOR INNER JOIN")
        strSQL.Append(" SAB_UACI_GARANTIASCONTRATOS AS GC ON SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = GC.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_CONTRATOS.IDPROVEEDOR = GC.IDPROVEEDOR AND SAB_UACI_CONTRATOS.IDCONTRATO = GC.IDCONTRATO AND ")
        strSQL.Append(" PRO.IDPROVEEDOR = GC.IDPROVEEDOR AND CPC.IDPROVEEDOR = GC.IDPROVEEDOR AND RO.IDPROVEEDOR = GC.IDPROVEEDOR AND ")
        strSQL.Append(" PC.IDESTABLECIMIENTO = GC.IDESTABLECIMIENTO AND RO.IDESTABLECIMIENTO = GC.IDESTABLECIMIENTO AND ")
        strSQL.Append(" CPC.IDCONTRATO = GC.IDCONTRATO INNER JOIN")
        strSQL.Append(" SAB_CAT_TIPOGARANTIAS AS TG ON GC.IDTIPOGARANTIA = TG.IDTIPOGARANTIA INNER JOIN")
        strSQL.Append(" SAB_CAT_ESTADOSGARANTIAS ON GC.IDESTADOGARANTIA = SAB_CAT_ESTADOSGARANTIAS.IDESTADOGARANTIA")
        strSQL.Append(" WHERE (SAB_UACI_CONTRATOS.IDESTABLECIMIENTO = @IDESTABLECIMIENTO) AND (GC.FECHAVENCIMIENTO = @FECHAVENCIMIENTO)")

        Dim args(2) As SqlParameter
        args(0) = New SqlParameter("@IDESTABLECIMIENTO", SqlDbType.Int)
        args(0).Value = IDESTABLECIMIENTO
        args(1) = New SqlParameter("@FECHAVENCIMIENTO", SqlDbType.DateTime)
        args(1).Value = FECHAVENCIMIENTO

        Dim ds As DataSet
        ds = SqlHelper.ExecuteDataset(Me.cnnStr, CommandType.Text, strSQL.ToString(), args)

        Return ds

    End Function

    Public Function obtenerGarantiaContrato(ByVal IDESTABLECIMIENTO As Integer, ByVal IDCONTRATO As Integer, ByVal IDPROVEEDOR As Integer, ByVal TIPOGARANTIA As Integer) As DataSet

        Dim strSQL As New Text.StringBuilder
        strSQL.Append(" SELECT SAB_UACI_GARANTIASCONTRATOS.IDESTABLECIMIENTO, SAB_UACI_GARANTIASCONTRATOS.IDPROVEEDOR, ")
        strSQL.Append(" SAB_UACI_GARANTIASCONTRATOS.IDCONTRATO, SAB_UACI_GARANTIASCONTRATOS.IDTIPOGARANTIA, SAB_CAT_TIPOGARANTIAS.NOMBRE, ")
        strSQL.Append(" MAX(SAB_UACI_GARANTIASCONTRATOS.IDGARANTIACONTRATO) AS Expr1, SAB_UACI_GARANTIASCONTRATOS.VIGENCIA, ")
        strSQL.Append(" SAB_UACI_GARANTIASCONTRATOS.PORCENTAJE, SAB_UACI_GARANTIASCONTRATOS.ENTREGA, SAB_UACI_CONTRATOS.MONTOCONTRATO ")
        strSQL.Append(" FROM SAB_UACI_GARANTIASCONTRATOS INNER JOIN ")
        strSQL.Append(" SAB_CAT_TIPOGARANTIAS ON SAB_UACI_GARANTIASCONTRATOS.IDTIPOGARANTIA = SAB_CAT_TIPOGARANTIAS.IDTIPOGARANTIA INNER JOIN ")
        strSQL.Append(" SAB_UACI_CONTRATOS ON SAB_UACI_GARANTIASCONTRATOS.IDESTABLECIMIENTO = SAB_UACI_CONTRATOS.IDESTABLECIMIENTO AND ")
        strSQL.Append(" SAB_UACI_GARANTIASCONTRATOS.IDPROVEEDOR = SAB_UACI_CONTRATOS.IDPROVEEDOR AND ")
        strSQL.Append(" SAB_UACI_GARANTIASCONTRATOS.IDCONTRATO = SAB_UACI_CONTRATOS.IDCONTRATO ")
        strSQL.Append(" GROUP BY SAB_UACI_GARANTIASCONTRATOS.IDESTABLECIMIENTO, SAB_UACI_GARANTIASCONTRATOS.IDPROVEEDOR, ")
        strSQL.Append(" SAB_UACI_GARANTIASCONTRATOS.IDCONTRATO, SAB_UACI_GARANTIASCONTRATOS.IDTIPOGARANTIA, SAB_CAT_TIPOGARANTIAS.NOMBRE, ")
        strSQL.Append(" SAB_UACI_GARANTIASCONTRATOS.VIGENCIA, SAB_UACI_GARANTIASCONTRATOS.PORCENTAJE, SAB_UACI_GARANTIASCONTRATOS.ENTREGA, ")
        strSQL.Append(" SAB_UACI_CONTRATOS.MONTOCONTRATO ")
        strSQL.Append(" HAVING (SAB_UACI_GARANTIASCONTRATOS.IDESTABLECIMIENTO = " & IDESTABLECIMIENTO & ") AND (SAB_UACI_GARANTIASCONTRATOS.IDPROVEEDOR = " & IDPROVEEDOR & ") AND ")
        strSQL.Append(" (SAB_UACI_GARANTIASCONTRATOS.IDCONTRATO = " & IDCONTRATO & ") AND (SAB_UACI_GARANTIASCONTRATOS.IDTIPOGARANTIA = " & TIPOGARANTIA & ") ")
        strSQL.Append(" ORDER BY Expr1 DESC ")

        Dim ds As DataSet
        ds = SqlHelper.ExecuteDataset(Me.cnnStr, CommandType.Text, strSQL.ToString())

        Return ds

    End Function

    Public Function validaExistenciaGarantia(ByVal IDESTABLECIMIENTO As Integer, ByVal IDPROVEEDOR As Integer, ByVal IDCONTRATO As Integer, ByVal IDTIPOGARANTIA As Integer) As Integer

        Dim strSQL As New Text.StringBuilder
        strSQL.Append(" SELECT IDGARANTIACONTRATO ")
        strSQL.Append(" FROM SAB_UACI_GARANTIASCONTRATOS ")
        strSQL.Append(" WHERE (IDESTABLECIMIENTO = " & IDESTABLECIMIENTO & ") AND (IDPROVEEDOR = " & IDPROVEEDOR & ") AND (IDCONTRATO = " & IDCONTRATO & ") AND (ESTASINCRONIZADA = 0) AND (IDTIPOGARANTIA = " & IDTIPOGARANTIA & ") ")

        Return SqlHelper.ExecuteScalar(Me.cnnStr, CommandType.Text, strSQL.ToString())

    End Function

    Public Function validaExistenciaGarantiaModificativa(ByVal IDESTABLECIMIENTO As Integer, ByVal IDPROVEEDOR As Integer, ByVal IDCONTRATO As Integer, ByVal IDTIPOGARANTIA As Integer, ByVal IDMODIFICATIVA As Integer) As Integer

        Dim strSQL As New Text.StringBuilder
        strSQL.Append(" SELECT IDGARANTIACONTRATO ")
        strSQL.Append(" FROM SAB_UACI_GARANTIASCONTRATOS ")
        strSQL.Append(" WHERE (IDESTABLECIMIENTO = " & IDESTABLECIMIENTO & ") AND (IDPROVEEDOR = " & IDPROVEEDOR & ") AND (IDCONTRATO = " & IDCONTRATO & ") AND (ESTASINCRONIZADA = 0) AND (IDTIPOGARANTIA = " & IDTIPOGARANTIA & ") AND (IDMODIFICATIVA = " & IDMODIFICATIVA & ")")

        Return SqlHelper.ExecuteScalar(Me.cnnStr, CommandType.Text, strSQL.ToString())

    End Function

#End Region

End Class
