'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("dsCATALOGOPRODUCTOS"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class dsCATALOGOPRODUCTOS
    Inherits Global.System.Data.DataSet
    
    Private tablevv_CATALOGOPRODUCTOS As vv_CATALOGOPRODUCTOSDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("vv_CATALOGOPRODUCTOS")) Is Nothing) Then
                MyBase.Tables.Add(New vv_CATALOGOPRODUCTOSDataTable(ds.Tables("vv_CATALOGOPRODUCTOS")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property vv_CATALOGOPRODUCTOS() As vv_CATALOGOPRODUCTOSDataTable
        Get
            Return Me.tablevv_CATALOGOPRODUCTOS
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As dsCATALOGOPRODUCTOS = CType(MyBase.Clone,dsCATALOGOPRODUCTOS)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXml(reader)
            If (Not (ds.Tables("vv_CATALOGOPRODUCTOS")) Is Nothing) Then
                MyBase.Tables.Add(New vv_CATALOGOPRODUCTOSDataTable(ds.Tables("vv_CATALOGOPRODUCTOS")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tablevv_CATALOGOPRODUCTOS = CType(MyBase.Tables("vv_CATALOGOPRODUCTOS"),vv_CATALOGOPRODUCTOSDataTable)
        If (initTable = true) Then
            If (Not (Me.tablevv_CATALOGOPRODUCTOS) Is Nothing) Then
                Me.tablevv_CATALOGOPRODUCTOS.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Sub InitClass()
        Me.DataSetName = "dsCATALOGOPRODUCTOS"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/dsCATALOGOPRODUCTOS.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tablevv_CATALOGOPRODUCTOS = New vv_CATALOGOPRODUCTOSDataTable()
        MyBase.Tables.Add(Me.tablevv_CATALOGOPRODUCTOS)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Function ShouldSerializevv_CATALOGOPRODUCTOS() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As dsCATALOGOPRODUCTOS = New dsCATALOGOPRODUCTOS()
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Delegate Sub vv_CATALOGOPRODUCTOSRowChangeEventHandler(ByVal sender As Object, ByVal e As vv_CATALOGOPRODUCTOSRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class vv_CATALOGOPRODUCTOSDataTable
        Inherits Global.System.Data.DataTable
        Implements Global.System.Collections.IEnumerable
        
        Private columnIDTIPOSUMINISTRO As Global.System.Data.DataColumn
        
        Private columnTIPOSUMINISTRO As Global.System.Data.DataColumn
        
        Private columnIDSUMINISTRO As Global.System.Data.DataColumn
        
        Private columnCORRSUMINISTRO As Global.System.Data.DataColumn
        
        Private columnDESCSUMINISTRO As Global.System.Data.DataColumn
        
        Private columnIDGRUPO As Global.System.Data.DataColumn
        
        Private columnCORRGRUPO As Global.System.Data.DataColumn
        
        Private columnDESCGRUPO As Global.System.Data.DataColumn
        
        Private columnIDSUBGRUPO As Global.System.Data.DataColumn
        
        Private columnCORRSUBGRUPO As Global.System.Data.DataColumn
        
        Private columnDESCSUBGRUPO As Global.System.Data.DataColumn
        
        Private columnIDPRODUCTO As Global.System.Data.DataColumn
        
        Private columnCORRPRODUCTO As Global.System.Data.DataColumn
        
        Private columnDESCPRODUCTO As Global.System.Data.DataColumn
        
        Private columnDESCLARGO As Global.System.Data.DataColumn
        
        Private columnIDNIVELUSO As Global.System.Data.DataColumn
        
        Private columnNOMBRECORTO As Global.System.Data.DataColumn
        
        Private columnPRECIOACTUAL As Global.System.Data.DataColumn
        
        Private columnEXISTENCIAACTUAL As Global.System.Data.DataColumn
        
        Private columnIDUNIDADMEDIDA As Global.System.Data.DataColumn
        
        Private columnDESCRIPCION As Global.System.Data.DataColumn
        
        Private columnUNIDADMEDIDA As Global.System.Data.DataColumn
        
        Private columnUNIDADESCONTENIDAS As Global.System.Data.DataColumn
        
        Private columnCANTIDADDECIMAL As Global.System.Data.DataColumn
        
        Private columnCODIGONACIONESUNIDAS As Global.System.Data.DataColumn
        
        Private columnCODIGONOMBRE As Global.System.Data.DataColumn
        
        Private columnALTERNATIVA As Global.System.Data.DataColumn
        
        Private columnIDESTABLECIMIENTO As Global.System.Data.DataColumn
        
        Private columnCLASIFICACION As Global.System.Data.DataColumn
        
        Private columnESPECIFICACIONESTECNICAS As Global.System.Data.DataColumn
        
        Private columnPERTENECELISTADOOFICIAL As Global.System.Data.DataColumn
        
        Private columnAREATECNICA As Global.System.Data.DataColumn
        
        Private columnTIPOUACI As Global.System.Data.DataColumn
        
        Private columnIDESPECIFICOGASTO As Global.System.Data.DataColumn
        
        Private columnNOMBREESPECIFICOGASTO As Global.System.Data.DataColumn
        
        Private columnCODIGOESPECIFICOGASTO As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "vv_CATALOGOPRODUCTOS"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property IDTIPOSUMINISTROColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnIDTIPOSUMINISTRO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property TIPOSUMINISTROColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTIPOSUMINISTRO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property IDSUMINISTROColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnIDSUMINISTRO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CORRSUMINISTROColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCORRSUMINISTRO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DESCSUMINISTROColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDESCSUMINISTRO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property IDGRUPOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnIDGRUPO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CORRGRUPOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCORRGRUPO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DESCGRUPOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDESCGRUPO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property IDSUBGRUPOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnIDSUBGRUPO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CORRSUBGRUPOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCORRSUBGRUPO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DESCSUBGRUPOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDESCSUBGRUPO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property IDPRODUCTOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnIDPRODUCTO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CORRPRODUCTOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCORRPRODUCTO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DESCPRODUCTOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDESCPRODUCTO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DESCLARGOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDESCLARGO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property IDNIVELUSOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnIDNIVELUSO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property NOMBRECORTOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnNOMBRECORTO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property PRECIOACTUALColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPRECIOACTUAL
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property EXISTENCIAACTUALColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnEXISTENCIAACTUAL
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property IDUNIDADMEDIDAColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnIDUNIDADMEDIDA
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DESCRIPCIONColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDESCRIPCION
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property UNIDADMEDIDAColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnUNIDADMEDIDA
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property UNIDADESCONTENIDASColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnUNIDADESCONTENIDAS
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CANTIDADDECIMALColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCANTIDADDECIMAL
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CODIGONACIONESUNIDASColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCODIGONACIONESUNIDAS
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CODIGONOMBREColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCODIGONOMBRE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property ALTERNATIVAColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnALTERNATIVA
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property IDESTABLECIMIENTOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnIDESTABLECIMIENTO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CLASIFICACIONColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCLASIFICACION
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property ESPECIFICACIONESTECNICASColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnESPECIFICACIONESTECNICAS
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property PERTENECELISTADOOFICIALColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPERTENECELISTADOOFICIAL
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property AREATECNICAColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAREATECNICA
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property TIPOUACIColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTIPOUACI
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property IDESPECIFICOGASTOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnIDESPECIFICOGASTO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property NOMBREESPECIFICOGASTOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnNOMBREESPECIFICOGASTO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CODIGOESPECIFICOGASTOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCODIGOESPECIFICOGASTO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As vv_CATALOGOPRODUCTOSRow
            Get
                Return CType(Me.Rows(index),vv_CATALOGOPRODUCTOSRow)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event vv_CATALOGOPRODUCTOSRowChanging As vv_CATALOGOPRODUCTOSRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event vv_CATALOGOPRODUCTOSRowChanged As vv_CATALOGOPRODUCTOSRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event vv_CATALOGOPRODUCTOSRowDeleting As vv_CATALOGOPRODUCTOSRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event vv_CATALOGOPRODUCTOSRowDeleted As vv_CATALOGOPRODUCTOSRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overloads Sub Addvv_CATALOGOPRODUCTOSRow(ByVal row As vv_CATALOGOPRODUCTOSRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overloads Function Addvv_CATALOGOPRODUCTOSRow( _
                    ByVal IDTIPOSUMINISTRO As Integer,  _
                    ByVal TIPOSUMINISTRO As String,  _
                    ByVal IDSUMINISTRO As Integer,  _
                    ByVal CORRSUMINISTRO As String,  _
                    ByVal DESCSUMINISTRO As String,  _
                    ByVal IDGRUPO As Integer,  _
                    ByVal CORRGRUPO As String,  _
                    ByVal DESCGRUPO As String,  _
                    ByVal IDSUBGRUPO As Integer,  _
                    ByVal CORRSUBGRUPO As String,  _
                    ByVal DESCSUBGRUPO As String,  _
                    ByVal IDPRODUCTO As Long,  _
                    ByVal CORRPRODUCTO As String,  _
                    ByVal DESCPRODUCTO As String,  _
                    ByVal DESCLARGO As String,  _
                    ByVal IDNIVELUSO As Byte,  _
                    ByVal NOMBRECORTO As String,  _
                    ByVal PRECIOACTUAL As Decimal,  _
                    ByVal EXISTENCIAACTUAL As Decimal,  _
                    ByVal IDUNIDADMEDIDA As Integer,  _
                    ByVal DESCRIPCION As String,  _
                    ByVal UNIDADMEDIDA As String,  _
                    ByVal UNIDADESCONTENIDAS As Integer,  _
                    ByVal CANTIDADDECIMAL As Byte,  _
                    ByVal CODIGONACIONESUNIDAS As String,  _
                    ByVal CODIGONOMBRE As String,  _
                    ByVal ALTERNATIVA As Integer,  _
                    ByVal IDESTABLECIMIENTO As Integer,  _
                    ByVal CLASIFICACION As String,  _
                    ByVal ESPECIFICACIONESTECNICAS As Byte,  _
                    ByVal PERTENECELISTADOOFICIAL As Byte,  _
                    ByVal AREATECNICA As Integer,  _
                    ByVal TIPOUACI As Integer,  _
                    ByVal IDESPECIFICOGASTO As Short,  _
                    ByVal NOMBREESPECIFICOGASTO As String,  _
                    ByVal CODIGOESPECIFICOGASTO As String) As vv_CATALOGOPRODUCTOSRow
            Dim rowvv_CATALOGOPRODUCTOSRow As vv_CATALOGOPRODUCTOSRow = CType(Me.NewRow,vv_CATALOGOPRODUCTOSRow)
            Dim columnValuesArray() As Object = New Object() {IDTIPOSUMINISTRO, TIPOSUMINISTRO, IDSUMINISTRO, CORRSUMINISTRO, DESCSUMINISTRO, IDGRUPO, CORRGRUPO, DESCGRUPO, IDSUBGRUPO, CORRSUBGRUPO, DESCSUBGRUPO, IDPRODUCTO, CORRPRODUCTO, DESCPRODUCTO, DESCLARGO, IDNIVELUSO, NOMBRECORTO, PRECIOACTUAL, EXISTENCIAACTUAL, IDUNIDADMEDIDA, DESCRIPCION, UNIDADMEDIDA, UNIDADESCONTENIDAS, CANTIDADDECIMAL, CODIGONACIONESUNIDAS, CODIGONOMBRE, ALTERNATIVA, IDESTABLECIMIENTO, CLASIFICACION, ESPECIFICACIONESTECNICAS, PERTENECELISTADOOFICIAL, AREATECNICA, TIPOUACI, IDESPECIFICOGASTO, NOMBREESPECIFICOGASTO, CODIGOESPECIFICOGASTO}
            rowvv_CATALOGOPRODUCTOSRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowvv_CATALOGOPRODUCTOSRow)
            Return rowvv_CATALOGOPRODUCTOSRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function FindByIDTIPOSUMINISTROIDSUMINISTROIDGRUPOIDSUBGRUPOIDPRODUCTOIDNIVELUSOIDUNIDADMEDIDA(ByVal IDTIPOSUMINISTRO As Integer, ByVal IDSUMINISTRO As Integer, ByVal IDGRUPO As Integer, ByVal IDSUBGRUPO As Integer, ByVal IDPRODUCTO As Long, ByVal IDNIVELUSO As Byte, ByVal IDUNIDADMEDIDA As Integer) As vv_CATALOGOPRODUCTOSRow
            Return CType(Me.Rows.Find(New Object() {IDTIPOSUMINISTRO, IDSUMINISTRO, IDGRUPO, IDSUBGRUPO, IDPRODUCTO, IDNIVELUSO, IDUNIDADMEDIDA}),vv_CATALOGOPRODUCTOSRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overridable Function GetEnumerator() As Global.System.Collections.IEnumerator Implements Global.System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As vv_CATALOGOPRODUCTOSDataTable = CType(MyBase.Clone,vv_CATALOGOPRODUCTOSDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New vv_CATALOGOPRODUCTOSDataTable()
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub InitVars()
            Me.columnIDTIPOSUMINISTRO = MyBase.Columns("IDTIPOSUMINISTRO")
            Me.columnTIPOSUMINISTRO = MyBase.Columns("TIPOSUMINISTRO")
            Me.columnIDSUMINISTRO = MyBase.Columns("IDSUMINISTRO")
            Me.columnCORRSUMINISTRO = MyBase.Columns("CORRSUMINISTRO")
            Me.columnDESCSUMINISTRO = MyBase.Columns("DESCSUMINISTRO")
            Me.columnIDGRUPO = MyBase.Columns("IDGRUPO")
            Me.columnCORRGRUPO = MyBase.Columns("CORRGRUPO")
            Me.columnDESCGRUPO = MyBase.Columns("DESCGRUPO")
            Me.columnIDSUBGRUPO = MyBase.Columns("IDSUBGRUPO")
            Me.columnCORRSUBGRUPO = MyBase.Columns("CORRSUBGRUPO")
            Me.columnDESCSUBGRUPO = MyBase.Columns("DESCSUBGRUPO")
            Me.columnIDPRODUCTO = MyBase.Columns("IDPRODUCTO")
            Me.columnCORRPRODUCTO = MyBase.Columns("CORRPRODUCTO")
            Me.columnDESCPRODUCTO = MyBase.Columns("DESCPRODUCTO")
            Me.columnDESCLARGO = MyBase.Columns("DESCLARGO")
            Me.columnIDNIVELUSO = MyBase.Columns("IDNIVELUSO")
            Me.columnNOMBRECORTO = MyBase.Columns("NOMBRECORTO")
            Me.columnPRECIOACTUAL = MyBase.Columns("PRECIOACTUAL")
            Me.columnEXISTENCIAACTUAL = MyBase.Columns("EXISTENCIAACTUAL")
            Me.columnIDUNIDADMEDIDA = MyBase.Columns("IDUNIDADMEDIDA")
            Me.columnDESCRIPCION = MyBase.Columns("DESCRIPCION")
            Me.columnUNIDADMEDIDA = MyBase.Columns("UNIDADMEDIDA")
            Me.columnUNIDADESCONTENIDAS = MyBase.Columns("UNIDADESCONTENIDAS")
            Me.columnCANTIDADDECIMAL = MyBase.Columns("CANTIDADDECIMAL")
            Me.columnCODIGONACIONESUNIDAS = MyBase.Columns("CODIGONACIONESUNIDAS")
            Me.columnCODIGONOMBRE = MyBase.Columns("CODIGONOMBRE")
            Me.columnALTERNATIVA = MyBase.Columns("ALTERNATIVA")
            Me.columnIDESTABLECIMIENTO = MyBase.Columns("IDESTABLECIMIENTO")
            Me.columnCLASIFICACION = MyBase.Columns("CLASIFICACION")
            Me.columnESPECIFICACIONESTECNICAS = MyBase.Columns("ESPECIFICACIONESTECNICAS")
            Me.columnPERTENECELISTADOOFICIAL = MyBase.Columns("PERTENECELISTADOOFICIAL")
            Me.columnAREATECNICA = MyBase.Columns("AREATECNICA")
            Me.columnTIPOUACI = MyBase.Columns("TIPOUACI")
            Me.columnIDESPECIFICOGASTO = MyBase.Columns("IDESPECIFICOGASTO")
            Me.columnNOMBREESPECIFICOGASTO = MyBase.Columns("NOMBREESPECIFICOGASTO")
            Me.columnCODIGOESPECIFICOGASTO = MyBase.Columns("CODIGOESPECIFICOGASTO")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Private Sub InitClass()
            Me.columnIDTIPOSUMINISTRO = New Global.System.Data.DataColumn("IDTIPOSUMINISTRO", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnIDTIPOSUMINISTRO)
            Me.columnTIPOSUMINISTRO = New Global.System.Data.DataColumn("TIPOSUMINISTRO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTIPOSUMINISTRO)
            Me.columnIDSUMINISTRO = New Global.System.Data.DataColumn("IDSUMINISTRO", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnIDSUMINISTRO)
            Me.columnCORRSUMINISTRO = New Global.System.Data.DataColumn("CORRSUMINISTRO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCORRSUMINISTRO)
            Me.columnDESCSUMINISTRO = New Global.System.Data.DataColumn("DESCSUMINISTRO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDESCSUMINISTRO)
            Me.columnIDGRUPO = New Global.System.Data.DataColumn("IDGRUPO", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnIDGRUPO)
            Me.columnCORRGRUPO = New Global.System.Data.DataColumn("CORRGRUPO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCORRGRUPO)
            Me.columnDESCGRUPO = New Global.System.Data.DataColumn("DESCGRUPO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDESCGRUPO)
            Me.columnIDSUBGRUPO = New Global.System.Data.DataColumn("IDSUBGRUPO", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnIDSUBGRUPO)
            Me.columnCORRSUBGRUPO = New Global.System.Data.DataColumn("CORRSUBGRUPO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCORRSUBGRUPO)
            Me.columnDESCSUBGRUPO = New Global.System.Data.DataColumn("DESCSUBGRUPO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDESCSUBGRUPO)
            Me.columnIDPRODUCTO = New Global.System.Data.DataColumn("IDPRODUCTO", GetType(Long), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnIDPRODUCTO)
            Me.columnCORRPRODUCTO = New Global.System.Data.DataColumn("CORRPRODUCTO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCORRPRODUCTO)
            Me.columnDESCPRODUCTO = New Global.System.Data.DataColumn("DESCPRODUCTO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDESCPRODUCTO)
            Me.columnDESCLARGO = New Global.System.Data.DataColumn("DESCLARGO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDESCLARGO)
            Me.columnIDNIVELUSO = New Global.System.Data.DataColumn("IDNIVELUSO", GetType(Byte), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnIDNIVELUSO)
            Me.columnNOMBRECORTO = New Global.System.Data.DataColumn("NOMBRECORTO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnNOMBRECORTO)
            Me.columnPRECIOACTUAL = New Global.System.Data.DataColumn("PRECIOACTUAL", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPRECIOACTUAL)
            Me.columnEXISTENCIAACTUAL = New Global.System.Data.DataColumn("EXISTENCIAACTUAL", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnEXISTENCIAACTUAL)
            Me.columnIDUNIDADMEDIDA = New Global.System.Data.DataColumn("IDUNIDADMEDIDA", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnIDUNIDADMEDIDA)
            Me.columnDESCRIPCION = New Global.System.Data.DataColumn("DESCRIPCION", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDESCRIPCION)
            Me.columnUNIDADMEDIDA = New Global.System.Data.DataColumn("UNIDADMEDIDA", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnUNIDADMEDIDA)
            Me.columnUNIDADESCONTENIDAS = New Global.System.Data.DataColumn("UNIDADESCONTENIDAS", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnUNIDADESCONTENIDAS)
            Me.columnCANTIDADDECIMAL = New Global.System.Data.DataColumn("CANTIDADDECIMAL", GetType(Byte), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCANTIDADDECIMAL)
            Me.columnCODIGONACIONESUNIDAS = New Global.System.Data.DataColumn("CODIGONACIONESUNIDAS", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCODIGONACIONESUNIDAS)
            Me.columnCODIGONOMBRE = New Global.System.Data.DataColumn("CODIGONOMBRE", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCODIGONOMBRE)
            Me.columnALTERNATIVA = New Global.System.Data.DataColumn("ALTERNATIVA", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnALTERNATIVA)
            Me.columnIDESTABLECIMIENTO = New Global.System.Data.DataColumn("IDESTABLECIMIENTO", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnIDESTABLECIMIENTO)
            Me.columnCLASIFICACION = New Global.System.Data.DataColumn("CLASIFICACION", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCLASIFICACION)
            Me.columnESPECIFICACIONESTECNICAS = New Global.System.Data.DataColumn("ESPECIFICACIONESTECNICAS", GetType(Byte), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnESPECIFICACIONESTECNICAS)
            Me.columnPERTENECELISTADOOFICIAL = New Global.System.Data.DataColumn("PERTENECELISTADOOFICIAL", GetType(Byte), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPERTENECELISTADOOFICIAL)
            Me.columnAREATECNICA = New Global.System.Data.DataColumn("AREATECNICA", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAREATECNICA)
            Me.columnTIPOUACI = New Global.System.Data.DataColumn("TIPOUACI", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTIPOUACI)
            Me.columnIDESPECIFICOGASTO = New Global.System.Data.DataColumn("IDESPECIFICOGASTO", GetType(Short), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnIDESPECIFICOGASTO)
            Me.columnNOMBREESPECIFICOGASTO = New Global.System.Data.DataColumn("NOMBREESPECIFICOGASTO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnNOMBREESPECIFICOGASTO)
            Me.columnCODIGOESPECIFICOGASTO = New Global.System.Data.DataColumn("CODIGOESPECIFICOGASTO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCODIGOESPECIFICOGASTO)
            Me.Constraints.Add(New Global.System.Data.UniqueConstraint("Constraint1", New Global.System.Data.DataColumn() {Me.columnIDTIPOSUMINISTRO, Me.columnIDSUMINISTRO, Me.columnIDGRUPO, Me.columnIDSUBGRUPO, Me.columnIDPRODUCTO, Me.columnIDNIVELUSO, Me.columnIDUNIDADMEDIDA}, true))
            Me.columnIDTIPOSUMINISTRO.AllowDBNull = false
            Me.columnTIPOSUMINISTRO.AllowDBNull = false
            Me.columnTIPOSUMINISTRO.MaxLength = 30
            Me.columnIDSUMINISTRO.AllowDBNull = false
            Me.columnCORRSUMINISTRO.AllowDBNull = false
            Me.columnCORRSUMINISTRO.MaxLength = 2
            Me.columnDESCSUMINISTRO.AllowDBNull = false
            Me.columnDESCSUMINISTRO.MaxLength = 40
            Me.columnIDGRUPO.AllowDBNull = false
            Me.columnCORRGRUPO.AllowDBNull = false
            Me.columnCORRGRUPO.MaxLength = 3
            Me.columnDESCGRUPO.AllowDBNull = false
            Me.columnDESCGRUPO.MaxLength = 60
            Me.columnIDSUBGRUPO.AllowDBNull = false
            Me.columnCORRSUBGRUPO.AllowDBNull = false
            Me.columnCORRSUBGRUPO.MaxLength = 3
            Me.columnDESCSUBGRUPO.ReadOnly = true
            Me.columnDESCSUBGRUPO.MaxLength = 8000
            Me.columnIDPRODUCTO.AllowDBNull = false
            Me.columnCORRPRODUCTO.AllowDBNull = false
            Me.columnCORRPRODUCTO.MaxLength = 8
            Me.columnDESCPRODUCTO.ReadOnly = true
            Me.columnDESCPRODUCTO.MaxLength = 8000
            Me.columnDESCLARGO.ReadOnly = true
            Me.columnDESCLARGO.MaxLength = 2147483647
            Me.columnIDNIVELUSO.AllowDBNull = false
            Me.columnNOMBRECORTO.AllowDBNull = false
            Me.columnNOMBRECORTO.MaxLength = 4
            Me.columnIDUNIDADMEDIDA.AllowDBNull = false
            Me.columnDESCRIPCION.AllowDBNull = false
            Me.columnDESCRIPCION.MaxLength = 6
            Me.columnUNIDADMEDIDA.AllowDBNull = false
            Me.columnUNIDADMEDIDA.MaxLength = 6
            Me.columnUNIDADESCONTENIDAS.AllowDBNull = false
            Me.columnCANTIDADDECIMAL.ReadOnly = true
            Me.columnCODIGONACIONESUNIDAS.MaxLength = 20
            Me.columnCODIGONOMBRE.ReadOnly = true
            Me.columnCODIGONOMBRE.MaxLength = 8000
            Me.columnALTERNATIVA.ReadOnly = true
            Me.columnCLASIFICACION.MaxLength = 1
            Me.columnESPECIFICACIONESTECNICAS.ReadOnly = true
            Me.columnPERTENECELISTADOOFICIAL.AllowDBNull = false
            Me.columnNOMBREESPECIFICOGASTO.ReadOnly = true
            Me.columnNOMBREESPECIFICOGASTO.MaxLength = 200
            Me.columnCODIGOESPECIFICOGASTO.ReadOnly = true
            Me.columnCODIGOESPECIFICOGASTO.MaxLength = 10
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function Newvv_CATALOGOPRODUCTOSRow() As vv_CATALOGOPRODUCTOSRow
            Return CType(Me.NewRow,vv_CATALOGOPRODUCTOSRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New vv_CATALOGOPRODUCTOSRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(vv_CATALOGOPRODUCTOSRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.vv_CATALOGOPRODUCTOSRowChangedEvent) Is Nothing) Then
                RaiseEvent vv_CATALOGOPRODUCTOSRowChanged(Me, New vv_CATALOGOPRODUCTOSRowChangeEvent(CType(e.Row,vv_CATALOGOPRODUCTOSRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.vv_CATALOGOPRODUCTOSRowChangingEvent) Is Nothing) Then
                RaiseEvent vv_CATALOGOPRODUCTOSRowChanging(Me, New vv_CATALOGOPRODUCTOSRowChangeEvent(CType(e.Row,vv_CATALOGOPRODUCTOSRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.vv_CATALOGOPRODUCTOSRowDeletedEvent) Is Nothing) Then
                RaiseEvent vv_CATALOGOPRODUCTOSRowDeleted(Me, New vv_CATALOGOPRODUCTOSRowChangeEvent(CType(e.Row,vv_CATALOGOPRODUCTOSRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.vv_CATALOGOPRODUCTOSRowDeletingEvent) Is Nothing) Then
                RaiseEvent vv_CATALOGOPRODUCTOSRowDeleting(Me, New vv_CATALOGOPRODUCTOSRowChangeEvent(CType(e.Row,vv_CATALOGOPRODUCTOSRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub Removevv_CATALOGOPRODUCTOSRow(ByVal row As vv_CATALOGOPRODUCTOSRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
            Dim ds As dsCATALOGOPRODUCTOS = New dsCATALOGOPRODUCTOS()
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "vv_CATALOGOPRODUCTOSDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    Partial Public Class vv_CATALOGOPRODUCTOSRow
        Inherits Global.System.Data.DataRow
        
        Private tablevv_CATALOGOPRODUCTOS As vv_CATALOGOPRODUCTOSDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tablevv_CATALOGOPRODUCTOS = CType(Me.Table,vv_CATALOGOPRODUCTOSDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property IDTIPOSUMINISTRO() As Integer
            Get
                Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.IDTIPOSUMINISTROColumn),Integer)
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.IDTIPOSUMINISTROColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property TIPOSUMINISTRO() As String
            Get
                Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.TIPOSUMINISTROColumn),String)
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.TIPOSUMINISTROColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property IDSUMINISTRO() As Integer
            Get
                Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.IDSUMINISTROColumn),Integer)
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.IDSUMINISTROColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CORRSUMINISTRO() As String
            Get
                Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.CORRSUMINISTROColumn),String)
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.CORRSUMINISTROColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DESCSUMINISTRO() As String
            Get
                Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.DESCSUMINISTROColumn),String)
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.DESCSUMINISTROColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property IDGRUPO() As Integer
            Get
                Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.IDGRUPOColumn),Integer)
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.IDGRUPOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CORRGRUPO() As String
            Get
                Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.CORRGRUPOColumn),String)
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.CORRGRUPOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DESCGRUPO() As String
            Get
                Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.DESCGRUPOColumn),String)
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.DESCGRUPOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property IDSUBGRUPO() As Integer
            Get
                Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.IDSUBGRUPOColumn),Integer)
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.IDSUBGRUPOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CORRSUBGRUPO() As String
            Get
                Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.CORRSUBGRUPOColumn),String)
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.CORRSUBGRUPOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DESCSUBGRUPO() As String
            Get
                Try 
                    Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.DESCSUBGRUPOColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DESCSUBGRUPO' in table 'vv_CATALOGOPRODUCTOS' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.DESCSUBGRUPOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property IDPRODUCTO() As Long
            Get
                Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.IDPRODUCTOColumn),Long)
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.IDPRODUCTOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CORRPRODUCTO() As String
            Get
                Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.CORRPRODUCTOColumn),String)
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.CORRPRODUCTOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DESCPRODUCTO() As String
            Get
                Try 
                    Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.DESCPRODUCTOColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DESCPRODUCTO' in table 'vv_CATALOGOPRODUCTOS' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.DESCPRODUCTOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DESCLARGO() As String
            Get
                Try 
                    Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.DESCLARGOColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DESCLARGO' in table 'vv_CATALOGOPRODUCTOS' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.DESCLARGOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property IDNIVELUSO() As Byte
            Get
                Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.IDNIVELUSOColumn),Byte)
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.IDNIVELUSOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property NOMBRECORTO() As String
            Get
                Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.NOMBRECORTOColumn),String)
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.NOMBRECORTOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property PRECIOACTUAL() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.PRECIOACTUALColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PRECIOACTUAL' in table 'vv_CATALOGOPRODUCTOS' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.PRECIOACTUALColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property EXISTENCIAACTUAL() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.EXISTENCIAACTUALColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'EXISTENCIAACTUAL' in table 'vv_CATALOGOPRODUCTOS' is DBNull"& _ 
                            ".", e)
                End Try
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.EXISTENCIAACTUALColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property IDUNIDADMEDIDA() As Integer
            Get
                Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.IDUNIDADMEDIDAColumn),Integer)
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.IDUNIDADMEDIDAColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DESCRIPCION() As String
            Get
                Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.DESCRIPCIONColumn),String)
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.DESCRIPCIONColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property UNIDADMEDIDA() As String
            Get
                Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.UNIDADMEDIDAColumn),String)
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.UNIDADMEDIDAColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property UNIDADESCONTENIDAS() As Integer
            Get
                Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.UNIDADESCONTENIDASColumn),Integer)
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.UNIDADESCONTENIDASColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CANTIDADDECIMAL() As Byte
            Get
                Try 
                    Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.CANTIDADDECIMALColumn),Byte)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CANTIDADDECIMAL' in table 'vv_CATALOGOPRODUCTOS' is DBNull."& _ 
                            "", e)
                End Try
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.CANTIDADDECIMALColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CODIGONACIONESUNIDAS() As String
            Get
                Try 
                    Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.CODIGONACIONESUNIDASColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CODIGONACIONESUNIDAS' in table 'vv_CATALOGOPRODUCTOS' is DB"& _ 
                            "Null.", e)
                End Try
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.CODIGONACIONESUNIDASColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CODIGONOMBRE() As String
            Get
                Try 
                    Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.CODIGONOMBREColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CODIGONOMBRE' in table 'vv_CATALOGOPRODUCTOS' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.CODIGONOMBREColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property ALTERNATIVA() As Integer
            Get
                Try 
                    Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.ALTERNATIVAColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ALTERNATIVA' in table 'vv_CATALOGOPRODUCTOS' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.ALTERNATIVAColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property IDESTABLECIMIENTO() As Integer
            Get
                Try 
                    Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.IDESTABLECIMIENTOColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'IDESTABLECIMIENTO' in table 'vv_CATALOGOPRODUCTOS' is DBNul"& _ 
                            "l.", e)
                End Try
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.IDESTABLECIMIENTOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CLASIFICACION() As String
            Get
                Try 
                    Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.CLASIFICACIONColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CLASIFICACION' in table 'vv_CATALOGOPRODUCTOS' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.CLASIFICACIONColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property ESPECIFICACIONESTECNICAS() As Byte
            Get
                Try 
                    Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.ESPECIFICACIONESTECNICASColumn),Byte)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ESPECIFICACIONESTECNICAS' in table 'vv_CATALOGOPRODUCTOS' i"& _ 
                            "s DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.ESPECIFICACIONESTECNICASColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property PERTENECELISTADOOFICIAL() As Byte
            Get
                Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.PERTENECELISTADOOFICIALColumn),Byte)
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.PERTENECELISTADOOFICIALColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property AREATECNICA() As Integer
            Get
                Try 
                    Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.AREATECNICAColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'AREATECNICA' in table 'vv_CATALOGOPRODUCTOS' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.AREATECNICAColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property TIPOUACI() As Integer
            Get
                Try 
                    Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.TIPOUACIColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'TIPOUACI' in table 'vv_CATALOGOPRODUCTOS' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.TIPOUACIColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property IDESPECIFICOGASTO() As Short
            Get
                Try 
                    Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.IDESPECIFICOGASTOColumn),Short)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'IDESPECIFICOGASTO' in table 'vv_CATALOGOPRODUCTOS' is DBNul"& _ 
                            "l.", e)
                End Try
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.IDESPECIFICOGASTOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property NOMBREESPECIFICOGASTO() As String
            Get
                Try 
                    Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.NOMBREESPECIFICOGASTOColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'NOMBREESPECIFICOGASTO' in table 'vv_CATALOGOPRODUCTOS' is D"& _ 
                            "BNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.NOMBREESPECIFICOGASTOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CODIGOESPECIFICOGASTO() As String
            Get
                Try 
                    Return CType(Me(Me.tablevv_CATALOGOPRODUCTOS.CODIGOESPECIFICOGASTOColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CODIGOESPECIFICOGASTO' in table 'vv_CATALOGOPRODUCTOS' is D"& _ 
                            "BNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablevv_CATALOGOPRODUCTOS.CODIGOESPECIFICOGASTOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsDESCSUBGRUPONull() As Boolean
            Return Me.IsNull(Me.tablevv_CATALOGOPRODUCTOS.DESCSUBGRUPOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetDESCSUBGRUPONull()
            Me(Me.tablevv_CATALOGOPRODUCTOS.DESCSUBGRUPOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsDESCPRODUCTONull() As Boolean
            Return Me.IsNull(Me.tablevv_CATALOGOPRODUCTOS.DESCPRODUCTOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetDESCPRODUCTONull()
            Me(Me.tablevv_CATALOGOPRODUCTOS.DESCPRODUCTOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsDESCLARGONull() As Boolean
            Return Me.IsNull(Me.tablevv_CATALOGOPRODUCTOS.DESCLARGOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetDESCLARGONull()
            Me(Me.tablevv_CATALOGOPRODUCTOS.DESCLARGOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsPRECIOACTUALNull() As Boolean
            Return Me.IsNull(Me.tablevv_CATALOGOPRODUCTOS.PRECIOACTUALColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetPRECIOACTUALNull()
            Me(Me.tablevv_CATALOGOPRODUCTOS.PRECIOACTUALColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsEXISTENCIAACTUALNull() As Boolean
            Return Me.IsNull(Me.tablevv_CATALOGOPRODUCTOS.EXISTENCIAACTUALColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetEXISTENCIAACTUALNull()
            Me(Me.tablevv_CATALOGOPRODUCTOS.EXISTENCIAACTUALColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsCANTIDADDECIMALNull() As Boolean
            Return Me.IsNull(Me.tablevv_CATALOGOPRODUCTOS.CANTIDADDECIMALColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetCANTIDADDECIMALNull()
            Me(Me.tablevv_CATALOGOPRODUCTOS.CANTIDADDECIMALColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsCODIGONACIONESUNIDASNull() As Boolean
            Return Me.IsNull(Me.tablevv_CATALOGOPRODUCTOS.CODIGONACIONESUNIDASColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetCODIGONACIONESUNIDASNull()
            Me(Me.tablevv_CATALOGOPRODUCTOS.CODIGONACIONESUNIDASColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsCODIGONOMBRENull() As Boolean
            Return Me.IsNull(Me.tablevv_CATALOGOPRODUCTOS.CODIGONOMBREColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetCODIGONOMBRENull()
            Me(Me.tablevv_CATALOGOPRODUCTOS.CODIGONOMBREColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsALTERNATIVANull() As Boolean
            Return Me.IsNull(Me.tablevv_CATALOGOPRODUCTOS.ALTERNATIVAColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetALTERNATIVANull()
            Me(Me.tablevv_CATALOGOPRODUCTOS.ALTERNATIVAColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsIDESTABLECIMIENTONull() As Boolean
            Return Me.IsNull(Me.tablevv_CATALOGOPRODUCTOS.IDESTABLECIMIENTOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetIDESTABLECIMIENTONull()
            Me(Me.tablevv_CATALOGOPRODUCTOS.IDESTABLECIMIENTOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsCLASIFICACIONNull() As Boolean
            Return Me.IsNull(Me.tablevv_CATALOGOPRODUCTOS.CLASIFICACIONColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetCLASIFICACIONNull()
            Me(Me.tablevv_CATALOGOPRODUCTOS.CLASIFICACIONColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsESPECIFICACIONESTECNICASNull() As Boolean
            Return Me.IsNull(Me.tablevv_CATALOGOPRODUCTOS.ESPECIFICACIONESTECNICASColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetESPECIFICACIONESTECNICASNull()
            Me(Me.tablevv_CATALOGOPRODUCTOS.ESPECIFICACIONESTECNICASColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsAREATECNICANull() As Boolean
            Return Me.IsNull(Me.tablevv_CATALOGOPRODUCTOS.AREATECNICAColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetAREATECNICANull()
            Me(Me.tablevv_CATALOGOPRODUCTOS.AREATECNICAColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsTIPOUACINull() As Boolean
            Return Me.IsNull(Me.tablevv_CATALOGOPRODUCTOS.TIPOUACIColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetTIPOUACINull()
            Me(Me.tablevv_CATALOGOPRODUCTOS.TIPOUACIColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsIDESPECIFICOGASTONull() As Boolean
            Return Me.IsNull(Me.tablevv_CATALOGOPRODUCTOS.IDESPECIFICOGASTOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetIDESPECIFICOGASTONull()
            Me(Me.tablevv_CATALOGOPRODUCTOS.IDESPECIFICOGASTOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsNOMBREESPECIFICOGASTONull() As Boolean
            Return Me.IsNull(Me.tablevv_CATALOGOPRODUCTOS.NOMBREESPECIFICOGASTOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetNOMBREESPECIFICOGASTONull()
            Me(Me.tablevv_CATALOGOPRODUCTOS.NOMBREESPECIFICOGASTOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsCODIGOESPECIFICOGASTONull() As Boolean
            Return Me.IsNull(Me.tablevv_CATALOGOPRODUCTOS.CODIGOESPECIFICOGASTOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetCODIGOESPECIFICOGASTONull()
            Me(Me.tablevv_CATALOGOPRODUCTOS.CODIGOESPECIFICOGASTOColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Class vv_CATALOGOPRODUCTOSRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As vv_CATALOGOPRODUCTOSRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub New(ByVal row As vv_CATALOGOPRODUCTOSRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property Row() As vv_CATALOGOPRODUCTOSRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
