//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace SINAB_Entidades
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class sceEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new sceEntities object using the connection string found in the 'sceEntities' section of the application configuration file.
        /// </summary>
        public sceEntities() : base("name=sceEntities", "sceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new sceEntities object.
        /// </summary>
        public sceEntities(string connectionString) : base(connectionString, "sceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new sceEntities object.
        /// </summary>
        public sceEntities(EntityConnection connection) : base(connection, "sceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vv_EstablecimientoRegion> vv_EstablecimientoRegion
        {
            get
            {
                if ((_vv_EstablecimientoRegion == null))
                {
                    _vv_EstablecimientoRegion = base.CreateObjectSet<vv_EstablecimientoRegion>("vv_EstablecimientoRegion");
                }
                return _vv_EstablecimientoRegion;
            }
        }
        private ObjectSet<vv_EstablecimientoRegion> _vv_EstablecimientoRegion;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vv_EstablecimientoRegion EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovv_EstablecimientoRegion(vv_EstablecimientoRegion vv_EstablecimientoRegion)
        {
            base.AddObject("vv_EstablecimientoRegion", vv_EstablecimientoRegion);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sceModel", Name="vv_EstablecimientoRegion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vv_EstablecimientoRegion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vv_EstablecimientoRegion object.
        /// </summary>
        /// <param name="idEstablecimiento">Initial value of the IdEstablecimiento property.</param>
        /// <param name="codigoEstablecimiento">Initial value of the CodigoEstablecimiento property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="idRegion">Initial value of the IdRegion property.</param>
        /// <param name="idEstablecimientoAbas">Initial value of the idEstablecimientoAbas property.</param>
        /// <param name="sibasi">Initial value of the sibasi property.</param>
        public static vv_EstablecimientoRegion Createvv_EstablecimientoRegion(global::System.Int16 idEstablecimiento, global::System.String codigoEstablecimiento, global::System.String nombre, global::System.Int16 idRegion, global::System.Int32 idEstablecimientoAbas, global::System.String sibasi)
        {
            vv_EstablecimientoRegion vv_EstablecimientoRegion = new vv_EstablecimientoRegion();
            vv_EstablecimientoRegion.IdEstablecimiento = idEstablecimiento;
            vv_EstablecimientoRegion.CodigoEstablecimiento = codigoEstablecimiento;
            vv_EstablecimientoRegion.Nombre = nombre;
            vv_EstablecimientoRegion.IdRegion = idRegion;
            vv_EstablecimientoRegion.idEstablecimientoAbas = idEstablecimientoAbas;
            vv_EstablecimientoRegion.sibasi = sibasi;
            return vv_EstablecimientoRegion;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 IdEstablecimiento
        {
            get
            {
                return _IdEstablecimiento;
            }
            set
            {
                if (_IdEstablecimiento != value)
                {
                    OnIdEstablecimientoChanging(value);
                    ReportPropertyChanging("IdEstablecimiento");
                    _IdEstablecimiento = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdEstablecimiento");
                    OnIdEstablecimientoChanged();
                }
            }
        }
        private global::System.Int16 _IdEstablecimiento;
        partial void OnIdEstablecimientoChanging(global::System.Int16 value);
        partial void OnIdEstablecimientoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CodigoEstablecimiento
        {
            get
            {
                return _CodigoEstablecimiento;
            }
            set
            {
                if (_CodigoEstablecimiento != value)
                {
                    OnCodigoEstablecimientoChanging(value);
                    ReportPropertyChanging("CodigoEstablecimiento");
                    _CodigoEstablecimiento = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CodigoEstablecimiento");
                    OnCodigoEstablecimientoChanged();
                }
            }
        }
        private global::System.String _CodigoEstablecimiento;
        partial void OnCodigoEstablecimientoChanging(global::System.String value);
        partial void OnCodigoEstablecimientoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                if (_Nombre != value)
                {
                    OnNombreChanging(value);
                    ReportPropertyChanging("Nombre");
                    _Nombre = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Nombre");
                    OnNombreChanged();
                }
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 IdRegion
        {
            get
            {
                return _IdRegion;
            }
            set
            {
                if (_IdRegion != value)
                {
                    OnIdRegionChanging(value);
                    ReportPropertyChanging("IdRegion");
                    _IdRegion = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdRegion");
                    OnIdRegionChanged();
                }
            }
        }
        private global::System.Int16 _IdRegion;
        partial void OnIdRegionChanging(global::System.Int16 value);
        partial void OnIdRegionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idEstablecimientoAbas
        {
            get
            {
                return _idEstablecimientoAbas;
            }
            set
            {
                if (_idEstablecimientoAbas != value)
                {
                    OnidEstablecimientoAbasChanging(value);
                    ReportPropertyChanging("idEstablecimientoAbas");
                    _idEstablecimientoAbas = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idEstablecimientoAbas");
                    OnidEstablecimientoAbasChanged();
                }
            }
        }
        private global::System.Int32 _idEstablecimientoAbas;
        partial void OnidEstablecimientoAbasChanging(global::System.Int32 value);
        partial void OnidEstablecimientoAbasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sibasi
        {
            get
            {
                return _sibasi;
            }
            set
            {
                if (_sibasi != value)
                {
                    OnsibasiChanging(value);
                    ReportPropertyChanging("sibasi");
                    _sibasi = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("sibasi");
                    OnsibasiChanged();
                }
            }
        }
        private global::System.String _sibasi;
        partial void OnsibasiChanging(global::System.String value);
        partial void OnsibasiChanged();

        #endregion

    
    }

    #endregion

    
}
